# Downloading Dataset

In [1]:
!pip install aicrowd-cli

Collecting aicrowd-cli
  Downloading https://files.pythonhosted.org/packages/1f/57/59b5a00c6e90c9cc028b3da9dff90e242ad2847e735b1a0e81a21c616e27/aicrowd_cli-0.1.7-py3-none-any.whl (49kB)
     |████████████████████████████████| 51kB 3.0MB/s
Requirement already satisfied: click<8,>=7.1.2 in /usr/local/lib/python3.7/dist-packages (from aicrowd-cli) (7.1.2)
Collecting requests-toolbelt<1,>=0.9.1
  Downloading https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl (54kB)
     |████████████████████████████████| 61kB 4.8MB/s
Collecting tqdm<5,>=4.56.0
  Downloading https://files.pythonhosted.org/packages/b4/20/9f1e974bb4761128fc0d0a32813eaa92827309b1756c4b892d28adfb4415/tqdm-4.61.1-py2.py3-none-any.whl (75kB)
     |████████████████████████████████| 81kB 5.3MB/s
Collecting rich<11,>=10.0.0
  Downloading https://files.pythonhosted.org/packages/a8/32/eb8aadb1ed791081e5c773bd1dfa15f1a71788fbeda37b12f837f2b1999b/rich-10.3.0-py3-none-any.whl (205kB)
     |████████████████████████████████| 215kB 8.8MB/s
Collecting requests<3,>=2.25.1
  Downloading https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61kB)
     |████████████████████████████████| 61kB 4.2MB/s
Requirement already satisfied: toml<1,>=0.10.2 in /usr/local/lib/python3.7/dist-packages (from aicrowd-cli) (0.10.2)
Collecting gitpython<4,>=3.1.12
  Downloading https://files.pythonhosted.org/packages/a6/99/98019716955ba243657daedd1de8f3a88ca1f5b75057c38e959db22fb87b/GitPython-3.1.14-py3-none-any.whl (159kB)
     |████████████████████████████████| 163kB 8.9MB/s
Collecting colorama<0.5.0,>=0.4.0
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Requirement already satisfied: typing-extensions<4.0.0,>=3.7.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from rich<11,>=10.0.0->aicrowd-cli) (3.7.4.3)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /usr/local/lib/python3.7/dist-packages (from rich<11,>=10.0.0->aicrowd-cli) (2.6.1)
Collecting commonmark<0.10.0,>=0.9.0
  Downloading https://files.pythonhosted.org/packages/b1/92/dfd892312d822f36c55366118b95d914e5f16de11044a27cf10a7d71bbbf/commonmark-0.9.1-py2.py3-none-any.whl (51kB)
     |████████████████████████████████| 51kB 4.3MB/s
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.25.1->aicrowd-cli) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.25.1->aicrowd-cli) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.25.1->aicrowd-cli) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.25.1->aicrowd-cli) (1.24.3)
Collecting gitdb<5,>=4.0.1
  Downloading https://files.pythonhosted.org/packages/ea/e8/f414d1a4f0bbc668ed441f74f44c116d9816833a48bf81d22b697090dba8/gitdb-4.0.7-py3-none-any.whl (63kB)
     |████████████████████████████████| 71kB 5.6MB/s
Collecting smmap<5,>=3.0.1
  Downloading https://files.pythonhosted.org/packages/68/ee/d540eb5e5996eb81c26ceffac6ee49041d473bc5125f2aa995cf51ec1cf1/smmap-4.0.0-py2.py3-none-any.whl
ERROR: google-colab 1.0.0 has requirement requests~=2.23.0, but you'll have requests 2.25.1 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
Installing collected packages: requests, requests-toolbelt, tqdm, colorama, commonmark, rich, smmap, gitdb, gitpython, aicrowd-cli
  Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Found existing installation: tqdm 4.41.1
    Uninstalling tqdm-4.41.1:
      Successfully uninstalled tqdm-4.41.1
Successfully installed aicrowd-cli-0.1.7 colorama-0.4.4 commonmark-0.9.1 gitdb-4.0.7 gitpython-3.1.14 requests-2.25.1 requests-toolbelt-0.9.1 rich-10.3.0 smmap-4.0.0 tqdm-4.61.1

In [2]:
API_KEY = 'cc0a3da7611cfc6098a7bd9db11b3ecf' # Please get your your API Key from [https://www.aicrowd.com/participants/me]
!aicrowd login --api-key $API_KEY

API Key valid
Saved API Key successfully!

In [3]:
# Downloading the Dataset
!mkdir data
!aicrowd dataset download --challenge emotion-detection -j 3 -o data

train.csv: 100% 2.30M/2.30M [00:00<00:00, 4.17MB/s]
test.csv:   0% 0.00/642k [00:00<?, ?B/s]
test.csv: 100% 642k/642k [00:00<00:00, 1.51MB/s]

val.csv: 100% 262k/262k [00:00<00:00, 808kB/s]

# Downloading & Importing Libraries

In [4]:
!pip install --upgrade spacy rich
!python -m spacy download en_core_web_sm # Downloaing the model for engligh language will contains many pretrained preprocessing pipelines

Collecting spacy
  Downloading https://files.pythonhosted.org/packages/1b/d8/0361bbaf7a1ff56b44dca04dace54c82d63dad7475b7d25ea1baefafafb2/spacy-3.0.6-cp37-cp37m-manylinux2014_x86_64.whl (12.8MB)
     |████████████████████████████████| 12.8MB 235kB/s
Requirement already up-to-date: rich in /usr/local/lib/python3.7/dist-packages (10.3.0)
Collecting srsly<3.0.0,>=2.4.1
  Downloading https://files.pythonhosted.org/packages/c3/84/dfdfc9f6f04f6b88207d96d9520b911e5fec0c67ff47a0dea31ab5429a1e/srsly-2.4.1-cp37-cp37m-manylinux2014_x86_64.whl (456kB)
     |████████████████████████████████| 460kB 29.6MB/s
Requirement already satisfied, skipping upgrade: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (4.61.1)
Collecting typer<0.4.0,>=0.3.0
  Downloading https://files.pythonhosted.org/packages/90/34/d138832f6945432c638f32137e6c79a3b682f06a63c488dcfaca6b166c64/typer-0.3.2-py3-none-any.whl
Requirement already satisfied, skipping upgrade: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.25.1)
Requirement already satisfied, skipping upgrade: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.19.5)
Collecting thinc<8.1.0,>=8.0.3
  Downloading https://files.pythonhosted.org/packages/39/82/b0f35c2013da8a372bb2948dc3fa0b840f71a8ed02bfe0b7809ae13271bc/thinc-8.0.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (618kB)
     |████████████████████████████████| 624kB 36.2MB/s
Requirement already satisfied, skipping upgrade: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.11.3)
Requirement already satisfied, skipping upgrade: blis<0.8.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.4.1)
Requirement already satisfied, skipping upgrade: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.5)
Requirement already satisfied, skipping upgrade: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.5)
Collecting spacy-legacy<3.1.0,>=3.0.4
  Downloading https://files.pythonhosted.org/packages/fa/a5/a727792d000b2a7bfcccbad03b292cd4c2d567d271fc3cab91250c2461e8/spacy_legacy-3.0.6-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: wasabi<1.1.0,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.8.2)
Collecting pathy>=0.3.5
  Downloading https://files.pythonhosted.org/packages/13/87/5991d87be8ed60beb172b4062dbafef18b32fa559635a8e2b633c2974f85/pathy-0.5.2-py3-none-any.whl (42kB)
     |████████████████████████████████| 51kB 4.9MB/s
Requirement already satisfied, skipping upgrade: typing-extensions<4.0.0.0,>=3.7.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from spacy) (3.7.4.3)
Collecting pydantic<1.8.0,>=1.7.1
  Downloading https://files.pythonhosted.org/packages/ca/fa/d43f31874e1f2a9633e4c025be310f2ce7a8350017579e9e837a62630a7e/pydantic-1.7.4-cp37-cp37m-manylinux2014_x86_64.whl (9.1MB)
     |████████████████████████████████| 9.1MB 33.5MB/s
Requirement already satisfied, skipping upgrade: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.5)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy) (57.0.0)
Requirement already satisfied, skipping upgrade: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (20.9)
Collecting catalogue<2.1.0,>=2.0.3
  Downloading https://files.pythonhosted.org/packages/9c/10/dbc1203a4b1367c7b02fddf08cb2981d9aa3e688d398f587cea0ab9e3bec/catalogue-2.0.4-py3-none-any.whl
Requirement already satisfied, skipping upgrade: colorama<0.5.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from rich) (0.4.4)
Requirement already satisfied, skipping upgrade: commonmark<0.10.0,>=0.9.0 in /usr/local/lib/python3.7/dist-packages (from rich) (0.9.1)
Requirement already satisfied, skipping upgrade: pygments<3.0.0,>=2.6.0 in /usr/local/lib/python3.7/dist-packages (from rich) (2.6.1)
Requirement already satisfied, skipping upgrade: click<7.2.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer<0.4.0,>=0.3.0->spacy) (7.1.2)
Requirement already satisfied, skipping upgrade: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (1.24.3)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.10)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2021.5.30)
Requirement already satisfied, skipping upgrade: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.4)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy) (2.0.1)
Collecting smart-open<4.0.0,>=2.2.0
  Downloading https://files.pythonhosted.org/packages/11/9a/ba2d5f67f25e8d5bbf2fcec7a99b1e38428e83cb715f64dd179ca43a11bb/smart_open-3.0.0.tar.gz (113kB)
     |████████████████████████████████| 122kB 53.0MB/s
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy) (2.4.7)
Requirement already satisfied, skipping upgrade: zipp>=0.5; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.3->spacy) (3.4.1)
Building wheels for collected packages: smart-open
  Building wheel for smart-open (setup.py) ... done
  Created wheel for smart-open: filename=smart_open-3.0.0-cp37-none-any.whl size=107107 sha256=09f82b1c142cf85fea4b371574288584a3b44bb3ba9e91fe289ee8cf8ae8d1bc
  Stored in directory: /root/.cache/pip/wheels/18/88/7c/f06dabd5e9cabe02d2269167bcacbbf9b47d0c0ff7d6ebcb78
Successfully built smart-open
Installing collected packages: catalogue, srsly, typer, pydantic, thinc, spacy-legacy, smart-open, pathy, spacy
  Found existing installation: catalogue 1.0.0
    Uninstalling catalogue-1.0.0:
      Successfully uninstalled catalogue-1.0.0
  Found existing installation: srsly 1.0.5
    Uninstalling srsly-1.0.5:
      Successfully uninstalled srsly-1.0.5
  Found existing installation: thinc 7.4.0
    Uninstalling thinc-7.4.0:
      Successfully uninstalled thinc-7.4.0
  Found existing installation: smart-open 5.1.0
    Uninstalling smart-open-5.1.0:
      Successfully uninstalled smart-open-5.1.0
  Found existing installation: spacy 2.2.4
    Uninstalling spacy-2.2.4:
      Successfully uninstalled spacy-2.2.4
Successfully installed catalogue-2.0.4 pathy-0.5.2 pydantic-1.7.4 smart-open-3.0.0 spacy-3.0.6 spacy-legacy-3.0.6 srsly-2.4.1 thinc-8.0.5 typer-0.3.2
2021-06-17 03:14:09.582002: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Collecting en-core-web-sm==3.0.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0-py3-none-any.whl (13.7MB)
     |████████████████████████████████| 13.7MB 203kB/s
Requirement already satisfied: spacy<3.1.0,>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from en-core-web-sm==3.0.0) (3.0.6)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (4.61.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.25.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (20.9)
Requirement already satisfied: wasabi<1.1.0,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (0.8.2)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (3.0.5)
Requirement already satisfied: pydantic<1.8.0,>=1.7.1 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (1.7.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (1.0.5)
Requirement already satisfied: catalogue<2.1.0,>=2.0.3 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.11.3)
Requirement already satisfied: typer<0.4.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (0.3.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (57.0.0)
Requirement already satisfied: typing-extensions<4.0.0.0,>=3.7.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (3.7.4.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.4 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (3.0.6)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (1.19.5)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.0.5)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (0.5.2)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (0.4.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.1 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.4.1)
Requirement already satisfied: thinc<8.1.0,>=8.0.3 in /usr/local/lib/python3.7/dist-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (8.0.5)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2021.5.30)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (1.24.3)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.4.7)
Requirement already satisfied: zipp>=0.5; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.3->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (3.4.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.0.1)
Requirement already satisfied: click<7.2.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer<0.4.0,>=0.3.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (7.1.2)
Requirement already satisfied: smart-open<4.0.0,>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (3.0.0)
Installing collected packages: en-core-web-sm
  Found existing installation: en-core-web-sm 2.2.5
    Uninstalling en-core-web-sm-2.2.5:
      Successfully uninstalled en-core-web-sm-2.2.5
Successfully installed en-core-web-sm-3.0.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [5]:
!curl https://raw.githubusercontent.com/tylerneylon/explacy/master/explacy.py -o explacy.py

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6896  100  6896    0     0  49257      0 --:--:-- --:--:-- --:--:-- 49257

In [6]:
import os
import time
import pandas as pd
import spacy
import explacy
import random
import numpy as np
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, accuracy_score

# To make things more beautiful! 
from rich.console import Console
from rich.table import Table
from rich import pretty
pretty.install()


# Seeding everything for getting same results 
random.seed(1)
spacy.util.fix_random_seed(1)

In [7]:
# spaCy v3.0 the the latest version spaCy 
spacy.__version__

'3.0.6'

# Reading Dataset

In [8]:
train_dataset = pd.read_csv("data/train.csv")
validation_dataset = pd.read_csv("data/val.csv")[1:]
test_dataset = pd.read_csv("data/test.csv")
train_dataset.head(20)

,text,label
0,takes no time to copy/paste a press release,0
1,You're delusional,1
2,Jazz fan here. I completely feel. Lindsay Mann...,0
3,ah i was also confused but i think they mean f...,0
4,Thank you so much. ♥️ that means a lot.,0
5,And I’ll be there!!!,0
6,There are some amazingly cringey compilations ...,0
7,Check the frame (FPS) limit option in the adva...,0
8,you made me think I was in the dbd subreddit w...,0
9,It was in your op.,0
10,There is a reason 15 people liked my comment d...,0
11,"He's not THAT bad on YouTube, but on Twitter.....",0
12,As someone who is dairy intolerant (milk is in...,0
13,IVE NEVER BEEN MORE PROUD TO CAMPAIGN FOR A CA...,0
14,See him live if you haven’t already. One of my...,0
15,CNN has video of the arrest. Someone needs to ...,0
16,"It wasn't fair on the rest of the list, nothin...",1
17,Finally got this in the mail today. I'm pretty...,0
18,"Yes, once I even deleted my account because I ...",1
19,This is truly the most captivating trilogy I’v...,0

In [9]:
train_dataset['label'].value_counts()

# Text Classification

In [10]:
nlp = spacy.load('en_core_web_sm')

In [11]:
# Getting a sample text from training dataset to demonstrate word2vec  
sample_text = train_dataset.iloc[2]['text'] 
sample_text

"Jazz fan here. I completely feel. Lindsay Mann cousins has more votes than Lindsay Mann, and Lindsay Mann hasn't even stepped on the court this year"

In [12]:
# Inputting the text in nlp function
doc = nlp(sample_text)

# Getting the embeddings from the sample text
doc.vector

array([ 0.5871044 ,  0.10283045,  0.23638554, -0.08171239,  0.02029083,
       -0.12000011, -0.1948305 ,  0.1250714 , -0.01082261, -0.34358275,
       -0.16639529, -0.04950966, -0.01394221,  0.06337869, -0.30135745,
        0.22211872, -0.17156254,  0.03178046,  0.30427024, -0.10826215,
       -0.25342506,  0.30617625, -0.17000276,  0.35598457, -0.00835321,
       -0.11478721, -0.1430562 ,  0.02518663,  0.60922873,  0.19284171,
       -0.23238468, -0.27463096, -0.13183063, -0.27534658,  0.25664884,
        0.05174499,  0.18620381,  0.11441176, -0.10955156,  0.29338667,
       -0.15877348, -0.02914245,  0.1963947 , -0.04410601,  0.12061837,
       -0.0941467 ,  0.27903876, -0.09223508, -0.00497099, -0.25587952,
        0.21098505,  0.01725493, -0.29827487,  0.0894304 ,  0.14340732,
       -0.0376591 , -0.3396481 ,  0.19914041,  0.28556582,  0.18212257,
        0.5140986 ,  0.02056837, -0.18578346, -0.28987882, -0.16651031,
       -0.10539112, -0.05578137,  0.00634063,  0.02737209,  0.14916842,
        0.15076284,  0.31409967, -0.06142968, -0.13555318, -0.08603293,
        0.40901124, -0.07265005, -0.19719984, -0.349496  ,  0.11685906,
        0.20542377,  0.1133521 ,  0.13061962,  0.2739835 , -0.00384022,
       -0.21771309, -0.28375924, -0.41814512, -0.42588463, -0.06813539,
       -0.27145588,  0.17521115, -0.15065633, -0.05529505,  0.06760314,
       -0.1013436 ], dtype=float32)

# Creating our Dataset

In [13]:
def create_data(dataset, is_train=True):

  # If we are using a training dataset
  if is_train == True:

    # Getting all text into a python list
    texts = list(dataset['text'].values)
                 
    # Put the list into the nlp pipeline and converting the output into a list
    preprocessed_texts = list(nlp.pipe(texts))

    # Getting vectors for all texts 
    X = [string.vector  for string in preprocessed_texts]

    # Labels for the corrosponding texts 
    y = dataset['label'].tolist()

    return X, y

  else:

    # Getting all text into a python list
    texts = list(dataset['text'].values)
                 
    # Put the list into the nlp pipeline and converting the output into a list
    preprocessed_texts = list(nlp.pipe(texts))

    # Getting vectors for all texts 
    X = [string.vector  for string in preprocessed_texts]

    return X

In [14]:
# Creating the training dataset
start_time = time.time()
X_train, y_train = create_data(train_dataset)
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

# Creating the validation dataset
start_time = time.time()
X_val, y_val = create_data(validation_dataset)
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

X_train[0], y_train[0]

Elapsed time: 66.8408 seconds
Elapsed time: 6.9152 seconds

(
    array([ 0.14151856, -0.05933758, -0.08044346, -0.1107378 ,  0.11325426,
        0.15893325, -0.44572473,  0.21314225,  0.07863858, -0.12423076,
        0.08870672, -0.16083065,  0.03217425, -0.18913928, -0.43932933,
        0.614143  , -0.04348904,  0.15507331, -0.10762676, -0.6841317 ,
       -0.52705824,  0.19307005,  0.5150874 , -0.78364027, -0.5798768 ,
       -0.36855024,  0.261396  ,  0.08007441,  0.13464396, -0.11683945,
       -0.40335947, -0.4810744 , -0.1996509 , -0.40538788,  0.907061  ,
       -0.08425845,  0.41184407, -0.05256712, -0.01928839,  0.67991185,
        0.18288395, -0.00932413,  0.15208176,  0.5218999 , -0.21960959,
       -0.0870916 ,  0.0571377 ,  0.39526838,  0.11505216,  0.03575191,
        0.18940884,  0.35989684, -0.03341857,  0.50211823,  0.25563306,
       -0.45388022,  0.04130013,  0.1111506 ,  0.11391255,  0.12924205,
       -0.44648582, -0.04701398, -0.12538372,  0.11663225,  0.3620197 ,
       -0.00661604, -0.25024778, -0.3998903 , -0.07583453,  0.747198  ,
        0.5959583 , -0.17592818, -0.04306039, -0.52941674, -0.12472894,
       -0.43728942, -0.06499843,  0.0685156 ,  0.23714057, -0.20262413,
        0.41856593,  0.01466806, -0.19088936,  0.36778176,  0.09763627,
       -0.3632294 , -0.15831968, -0.43174067, -0.08282916, -0.09869532,
        0.14616643,  0.02205803, -0.33136448,  0.19892709, -0.50562334,
       -0.14163868], dtype=float32),
    0
)

# Training the Model

In [23]:
X_train = np.array(X_train)
X_val = np.array(X_val)
y_train = np.array(y_train)
y_val = np.array(y_val)

print(X_train.shape)
print(X_val.shape)
print(y_train.shape)
print(y_val.shape)

(31255, 96)
(3472, 96)
(31255,)
(3472,)

In [24]:
model = XGBClassifier(
    n_estimators=1000, subsample=0.8, colsample_bytree=0.8,
    objective='binary:logistic', scale_pos_weight=4,
    seed=27
)
eval_set = [(X_val, y_val)]

model.fit(X_train, y_train, early_stopping_rounds=50,
          eval_metric="auc", eval_set=eval_set, verbose=True)

[0]	validation_0-auc:0.559508
Will train until validation_0-auc hasn't improved in 50 rounds.
[1]	validation_0-auc:0.569899
[2]	validation_0-auc:0.569146
[3]	validation_0-auc:0.572955
[4]	validation_0-auc:0.572721
[5]	validation_0-auc:0.576952
[6]	validation_0-auc:0.576486
[7]	validation_0-auc:0.577246
[8]	validation_0-auc:0.580862
[9]	validation_0-auc:0.582619
[10]	validation_0-auc:0.582515
[11]	validation_0-auc:0.585837
[12]	validation_0-auc:0.588232
[13]	validation_0-auc:0.587736
[14]	validation_0-auc:0.590206
[15]	validation_0-auc:0.591812
[16]	validation_0-auc:0.591587
[17]	validation_0-auc:0.593207
[18]	validation_0-auc:0.594562
[19]	validation_0-auc:0.595734
[20]	validation_0-auc:0.597291
[21]	validation_0-auc:0.597657
[22]	validation_0-auc:0.599209
[23]	validation_0-auc:0.600187
[24]	validation_0-auc:0.602087
[25]	validation_0-auc:0.600884
[26]	validation_0-auc:0.60205
[27]	validation_0-auc:0.601949
[28]	validation_0-auc:0.602843
[29]	validation_0-auc:0.606184
[30]	validation_0-auc:0.605475
[31]	validation_0-auc:0.603701
[32]	validation_0-auc:0.604443
[33]	validation_0-auc:0.605955
[34]	validation_0-auc:0.606712
[35]	validation_0-auc:0.606811
[36]	validation_0-auc:0.607008
[37]	validation_0-auc:0.60664
[38]	validation_0-auc:0.605098
[39]	validation_0-auc:0.604789
[40]	validation_0-auc:0.604913
[41]	validation_0-auc:0.605352
[42]	validation_0-auc:0.605084
[43]	validation_0-auc:0.605561
[44]	validation_0-auc:0.605802
[45]	validation_0-auc:0.605305
[46]	validation_0-auc:0.605505
[47]	validation_0-auc:0.60614
[48]	validation_0-auc:0.60669
[49]	validation_0-auc:0.606245
[50]	validation_0-auc:0.60529
[51]	validation_0-auc:0.606251
[52]	validation_0-auc:0.606028
[53]	validation_0-auc:0.60698
[54]	validation_0-auc:0.607285
[55]	validation_0-auc:0.608206
[56]	validation_0-auc:0.608549
[57]	validation_0-auc:0.608789
[58]	validation_0-auc:0.609214
[59]	validation_0-auc:0.609449
[60]	validation_0-auc:0.609624
[61]	validation_0-auc:0.609893
[62]	validation_0-auc:0.611662
[63]	validation_0-auc:0.611816
[64]	validation_0-auc:0.611578
[65]	validation_0-auc:0.61305
[66]	validation_0-auc:0.613802
[67]	validation_0-auc:0.614101
[68]	validation_0-auc:0.614404
[69]	validation_0-auc:0.615008
[70]	validation_0-auc:0.614915
[71]	validation_0-auc:0.61467
[72]	validation_0-auc:0.614977
[73]	validation_0-auc:0.61542
[74]	validation_0-auc:0.615938
[75]	validation_0-auc:0.615806
[76]	validation_0-auc:0.616176
[77]	validation_0-auc:0.617696
[78]	validation_0-auc:0.617572
[79]	validation_0-auc:0.618659
[80]	validation_0-auc:0.619047
[81]	validation_0-auc:0.618486
[82]	validation_0-auc:0.618284
[83]	validation_0-auc:0.618262
[84]	validation_0-auc:0.618634
[85]	validation_0-auc:0.618974
[86]	validation_0-auc:0.618572
[87]	validation_0-auc:0.61919
[88]	validation_0-auc:0.619246
[89]	validation_0-auc:0.619486
[90]	validation_0-auc:0.621031
[91]	validation_0-auc:0.622014
[92]	validation_0-auc:0.621906
[93]	validation_0-auc:0.621988
[94]	validation_0-auc:0.622145
[95]	validation_0-auc:0.621966
[96]	validation_0-auc:0.622133
[97]	validation_0-auc:0.622516
[98]	validation_0-auc:0.622101
[99]	validation_0-auc:0.622138
[100]	validation_0-auc:0.62221
[101]	validation_0-auc:0.622284
[102]	validation_0-auc:0.622302
[103]	validation_0-auc:0.622433
[104]	validation_0-auc:0.623602
[105]	validation_0-auc:0.623685
[106]	validation_0-auc:0.623096
[107]	validation_0-auc:0.62258
[108]	validation_0-auc:0.622556
[109]	validation_0-auc:0.622867
[110]	validation_0-auc:0.622663
[111]	validation_0-auc:0.622147
[112]	validation_0-auc:0.622196
[113]	validation_0-auc:0.622128
[114]	validation_0-auc:0.622065
[115]	validation_0-auc:0.62172
[116]	validation_0-auc:0.622418
[117]	validation_0-auc:0.621763
[118]	validation_0-auc:0.622287
[119]	validation_0-auc:0.622252
[120]	validation_0-auc:0.62213
[121]	validation_0-auc:0.621996
[122]	validation_0-auc:0.622611
[123]	validation_0-auc:0.622984
[124]	validation_0-auc:0.622925
[125]	validation_0-auc:0.62351
[126]	validation_0-auc:0.623259
[127]	validation_0-auc:0.623165
[128]	validation_0-auc:0.623183
[129]	validation_0-auc:0.622987
[130]	validation_0-auc:0.623707
[131]	validation_0-auc:0.623806
[132]	validation_0-auc:0.623729
[133]	validation_0-auc:0.623936
[134]	validation_0-auc:0.623466
[135]	validation_0-auc:0.623892
[136]	validation_0-auc:0.62417
[137]	validation_0-auc:0.624711
[138]	validation_0-auc:0.624677
[139]	validation_0-auc:0.62506
[140]	validation_0-auc:0.624435
[141]	validation_0-auc:0.624503
[142]	validation_0-auc:0.624542
[143]	validation_0-auc:0.624758
[144]	validation_0-auc:0.62454
[145]	validation_0-auc:0.624761
[146]	validation_0-auc:0.624541
[147]	validation_0-auc:0.624781
[148]	validation_0-auc:0.625543
[149]	validation_0-auc:0.625352
[150]	validation_0-auc:0.624897
[151]	validation_0-auc:0.62483
[152]	validation_0-auc:0.624265
[153]	validation_0-auc:0.624226
[154]	validation_0-auc:0.624168
[155]	validation_0-auc:0.624831
[156]	validation_0-auc:0.624933
[157]	validation_0-auc:0.624593
[158]	validation_0-auc:0.624297
[159]	validation_0-auc:0.624459
[160]	validation_0-auc:0.624412
[161]	validation_0-auc:0.624126
[162]	validation_0-auc:0.624132
[163]	validation_0-auc:0.624011
[164]	validation_0-auc:0.623606
[165]	validation_0-auc:0.623936
[166]	validation_0-auc:0.624385
[167]	validation_0-auc:0.624241
[168]	validation_0-auc:0.624347
[169]	validation_0-auc:0.623776
[170]	validation_0-auc:0.623832
[171]	validation_0-auc:0.624823
[172]	validation_0-auc:0.624582
[173]	validation_0-auc:0.625004
[174]	validation_0-auc:0.625008
[175]	validation_0-auc:0.625528
[176]	validation_0-auc:0.625934
[177]	validation_0-auc:0.626094
[178]	validation_0-auc:0.625731
[179]	validation_0-auc:0.625731
[180]	validation_0-auc:0.625808
[181]	validation_0-auc:0.625843
[182]	validation_0-auc:0.625779
[183]	validation_0-auc:0.625805
[184]	validation_0-auc:0.625719
[185]	validation_0-auc:0.625887
[186]	validation_0-auc:0.626156
[187]	validation_0-auc:0.626075
[188]	validation_0-auc:0.625892
[189]	validation_0-auc:0.626064
[190]	validation_0-auc:0.625647
[191]	validation_0-auc:0.62549
[192]	validation_0-auc:0.625587
[193]	validation_0-auc:0.625124
[194]	validation_0-auc:0.625471
[195]	validation_0-auc:0.625729
[196]	validation_0-auc:0.625995
[197]	validation_0-auc:0.626134
[198]	validation_0-auc:0.625526
[199]	validation_0-auc:0.625604
[200]	validation_0-auc:0.625308
[201]	validation_0-auc:0.625776
[202]	validation_0-auc:0.625775
[203]	validation_0-auc:0.626139
[204]	validation_0-auc:0.626067
[205]	validation_0-auc:0.62631
[206]	validation_0-auc:0.626192
[207]	validation_0-auc:0.625518
[208]	validation_0-auc:0.626314
[209]	validation_0-auc:0.626974
[210]	validation_0-auc:0.62675
[211]	validation_0-auc:0.626659
[212]	validation_0-auc:0.626459
[213]	validation_0-auc:0.626153
[214]	validation_0-auc:0.626002
[215]	validation_0-auc:0.626041
[216]	validation_0-auc:0.626147
[217]	validation_0-auc:0.625998
[218]	validation_0-auc:0.625745
[219]	validation_0-auc:0.625603
[220]	validation_0-auc:0.625865
[221]	validation_0-auc:0.625528
[222]	validation_0-auc:0.625869
[223]	validation_0-auc:0.626453
[224]	validation_0-auc:0.626738
[225]	validation_0-auc:0.626702
[226]	validation_0-auc:0.626626
[227]	validation_0-auc:0.626528
[228]	validation_0-auc:0.626233
[229]	validation_0-auc:0.626438
[230]	validation_0-auc:0.626768
[231]	validation_0-auc:0.626465
[232]	validation_0-auc:0.626623
[233]	validation_0-auc:0.626859
[234]	validation_0-auc:0.626228
[235]	validation_0-auc:0.626567
[236]	validation_0-auc:0.626458
[237]	validation_0-auc:0.626477
[238]	validation_0-auc:0.626516
[239]	validation_0-auc:0.626297
[240]	validation_0-auc:0.626463
[241]	validation_0-auc:0.626506
[242]	validation_0-auc:0.626469
[243]	validation_0-auc:0.626721
[244]	validation_0-auc:0.626746
[245]	validation_0-auc:0.626865
[246]	validation_0-auc:0.627081
[247]	validation_0-auc:0.626808
[248]	validation_0-auc:0.626823
[249]	validation_0-auc:0.626617
[250]	validation_0-auc:0.62628
[251]	validation_0-auc:0.626476
[252]	validation_0-auc:0.626684
[253]	validation_0-auc:0.626658
[254]	validation_0-auc:0.626511
[255]	validation_0-auc:0.62675
[256]	validation_0-auc:0.627639
[257]	validation_0-auc:0.627385
[258]	validation_0-auc:0.628109
[259]	validation_0-auc:0.628232
[260]	validation_0-auc:0.628572
[261]	validation_0-auc:0.628603
[262]	validation_0-auc:0.62842
[263]	validation_0-auc:0.628457
[264]	validation_0-auc:0.628563
[265]	validation_0-auc:0.628349
[266]	validation_0-auc:0.628039
[267]	validation_0-auc:0.628042
[268]	validation_0-auc:0.628488
[269]	validation_0-auc:0.628041
[270]	validation_0-auc:0.628371
[271]	validation_0-auc:0.628571
[272]	validation_0-auc:0.628379
[273]	validation_0-auc:0.628598
[274]	validation_0-auc:0.628752
[275]	validation_0-auc:0.628591
[276]	validation_0-auc:0.628539
[277]	validation_0-auc:0.628425
[278]	validation_0-auc:0.628333
[279]	validation_0-auc:0.627943
[280]	validation_0-auc:0.627585
[281]	validation_0-auc:0.627676
[282]	validation_0-auc:0.627989
[283]	validation_0-auc:0.628117
[284]	validation_0-auc:0.628295
[285]	validation_0-auc:0.628122
[286]	validation_0-auc:0.62834
[287]	validation_0-auc:0.628227
[288]	validation_0-auc:0.628597
[289]	validation_0-auc:0.62847
[290]	validation_0-auc:0.628443
[291]	validation_0-auc:0.628202
[292]	validation_0-auc:0.628067
[293]	validation_0-auc:0.628696
[294]	validation_0-auc:0.629107
[295]	validation_0-auc:0.629518
[296]	validation_0-auc:0.629822
[297]	validation_0-auc:0.629908
[298]	validation_0-auc:0.63027
[299]	validation_0-auc:0.629735
[300]	validation_0-auc:0.629377
[301]	validation_0-auc:0.629241
[302]	validation_0-auc:0.62922
[303]	validation_0-auc:0.628868
[304]	validation_0-auc:0.628718
[305]	validation_0-auc:0.628945
[306]	validation_0-auc:0.628386
[307]	validation_0-auc:0.62842
[308]	validation_0-auc:0.627644
[309]	validation_0-auc:0.627806
[310]	validation_0-auc:0.628095
[311]	validation_0-auc:0.628378
[312]	validation_0-auc:0.628239
[313]	validation_0-auc:0.628367
[314]	validation_0-auc:0.627846
[315]	validation_0-auc:0.627721
[316]	validation_0-auc:0.62776
[317]	validation_0-auc:0.627855
[318]	validation_0-auc:0.62812
[319]	validation_0-auc:0.628002
[320]	validation_0-auc:0.628109
[321]	validation_0-auc:0.628633
[322]	validation_0-auc:0.628361
[323]	validation_0-auc:0.628529
[324]	validation_0-auc:0.628479
[325]	validation_0-auc:0.628404
[326]	validation_0-auc:0.628254
[327]	validation_0-auc:0.628245
[328]	validation_0-auc:0.628412
[329]	validation_0-auc:0.628293
[330]	validation_0-auc:0.627965
[331]	validation_0-auc:0.627794
[332]	validation_0-auc:0.628172
[333]	validation_0-auc:0.628707
[334]	validation_0-auc:0.628712
[335]	validation_0-auc:0.628957
[336]	validation_0-auc:0.628805
[337]	validation_0-auc:0.629052
[338]	validation_0-auc:0.629147
[339]	validation_0-auc:0.629364
[340]	validation_0-auc:0.629507
[341]	validation_0-auc:0.629673
[342]	validation_0-auc:0.630009
[343]	validation_0-auc:0.629866
[344]	validation_0-auc:0.630205
[345]	validation_0-auc:0.630281
[346]	validation_0-auc:0.630152
[347]	validation_0-auc:0.630516
[348]	validation_0-auc:0.63043
[349]	validation_0-auc:0.630265
[350]	validation_0-auc:0.630632
[351]	validation_0-auc:0.630542
[352]	validation_0-auc:0.63063
[353]	validation_0-auc:0.631015
[354]	validation_0-auc:0.631007
[355]	validation_0-auc:0.630979
[356]	validation_0-auc:0.631178
[357]	validation_0-auc:0.63099
[358]	validation_0-auc:0.630929
[359]	validation_0-auc:0.630887
[360]	validation_0-auc:0.630996
[361]	validation_0-auc:0.630558
[362]	validation_0-auc:0.630466
[363]	validation_0-auc:0.630581
[364]	validation_0-auc:0.630277
[365]	validation_0-auc:0.6307
[366]	validation_0-auc:0.630274
[367]	validation_0-auc:0.63017
[368]	validation_0-auc:0.629921
[369]	validation_0-auc:0.630047
[370]	validation_0-auc:0.630203
[371]	validation_0-auc:0.630512
[372]	validation_0-auc:0.63079
[373]	validation_0-auc:0.630749
[374]	validation_0-auc:0.630555
[375]	validation_0-auc:0.630025
[376]	validation_0-auc:0.630127
[377]	validation_0-auc:0.630245
[378]	validation_0-auc:0.63036
[379]	validation_0-auc:0.630287
[380]	validation_0-auc:0.630146
[381]	validation_0-auc:0.630072
[382]	validation_0-auc:0.63019
[383]	validation_0-auc:0.630049
[384]	validation_0-auc:0.630677
[385]	validation_0-auc:0.630299
[386]	validation_0-auc:0.63033
[387]	validation_0-auc:0.630475
[388]	validation_0-auc:0.631068
[389]	validation_0-auc:0.631299
[390]	validation_0-auc:0.631273
[391]	validation_0-auc:0.631301
[392]	validation_0-auc:0.631485
[393]	validation_0-auc:0.631513
[394]	validation_0-auc:0.631116
[395]	validation_0-auc:0.63118
[396]	validation_0-auc:0.631155
[397]	validation_0-auc:0.631112
[398]	validation_0-auc:0.630681
[399]	validation_0-auc:0.630705
[400]	validation_0-auc:0.630595
[401]	validation_0-auc:0.630209
[402]	validation_0-auc:0.630234
[403]	validation_0-auc:0.629835
[404]	validation_0-auc:0.630051
[405]	validation_0-auc:0.630065
[406]	validation_0-auc:0.629966
[407]	validation_0-auc:0.629801
[408]	validation_0-auc:0.629927
[409]	validation_0-auc:0.629916
[410]	validation_0-auc:0.630194
[411]	validation_0-auc:0.630021
[412]	validation_0-auc:0.630354
[413]	validation_0-auc:0.630277
[414]	validation_0-auc:0.630145
[415]	validation_0-auc:0.630317
[416]	validation_0-auc:0.630262
[417]	validation_0-auc:0.63033
[418]	validation_0-auc:0.630352
[419]	validation_0-auc:0.630186
[420]	validation_0-auc:0.63047
[421]	validation_0-auc:0.630298
[422]	validation_0-auc:0.63049
[423]	validation_0-auc:0.630942
[424]	validation_0-auc:0.631256
[425]	validation_0-auc:0.631396
[426]	validation_0-auc:0.631185
[427]	validation_0-auc:0.631131
[428]	validation_0-auc:0.631095
[429]	validation_0-auc:0.630741
[430]	validation_0-auc:0.630381
[431]	validation_0-auc:0.630238
[432]	validation_0-auc:0.630215
[433]	validation_0-auc:0.630245
[434]	validation_0-auc:0.630582
[435]	validation_0-auc:0.630998
[436]	validation_0-auc:0.63088
[437]	validation_0-auc:0.630821
[438]	validation_0-auc:0.630658
[439]	validation_0-auc:0.630479
[440]	validation_0-auc:0.6307
[441]	validation_0-auc:0.630913
[442]	validation_0-auc:0.63122
[443]	validation_0-auc:0.63114
Stopping. Best iteration:
[393]	validation_0-auc:0.631513

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.8, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=1000, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=4, seed=27,
              silent=None, subsample=0.8, verbosity=1)

# Evaluation

In [26]:
y_pred = model.predict(X_train)

# Getting F1 & Accuracy score of training predictions
f1 = f1_score(y_train, y_pred)
accuracy = accuracy_score(y_train, y_pred)

print(f"Training F1 Score  : {round(f1, 4)} and Accuracy Score {round(accuracy, 4)}")

Training F1 Score  : 0.5325 and Accuracy Score 0.7017

In [28]:
y_pred = model.predict(X_val)

# Getting F1 & Accuracy score of validation predictions
f1 = f1_score(y_val, y_pred)
accuracy = accuracy_score(y_val, y_pred)

print(f"Validation F1 Score  : {round(f1, 4)} and Accuracy Score {round(accuracy, 4)}")

Validation F1 Score  : 0.3738 and Accuracy Score 0.6005

# Submitting Results

In [29]:
# By settings is_train=False, the create_data function will only output the features as setuped in the function

start_time = time.time()
test_data = create_data(test_dataset, is_train=False)
test_data = np.array(test_data)

test_predictions = model.predict(test_data)
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

Elapsed time: 17.8621 seconds

In [30]:
# Applying the predictions to the labels column of the sample submission 
test_dataset['label'] = test_predictions
print(test_dataset.shape)

test_dataset.head(20)

(8682, 2)

,text,label
0,I was already over the edge with Cassie Zamora...,0
1,I think you're right. She has oodles of cash a...,1
2,Haha I love this. I used to give mine phone bo...,0
3,Probably out of desperation as they going no a...,1
4,Sorry !! You’re real good at that!!,0
5,I say we get the pitch forks and make him have...,0
6,He looks really different now.,0
7,I swear people just want to be angry,1
8,lol robot car,0
9,Yeah I’ve been watching these videos and they ...,1
10,Stranger things have happened.,0
11,No you pick a different hero. Aint fkn rocket ...,1
12,Was this tattoo designed by Desiree Erickson?,0
13,Not unexpected this election was gonna be a br...,1
14,Come to Nashville. Love to help with that prob...,0
15,they're a bit expensive anyways,1
16,"No, it isn't K.",1
17,Wow! It's dead af here,0
18,Thankyou! Good luck with your search! An AP is...,0
19,This spoke to my soul. I might cry 😭. I really...,1

In [31]:
!mkdir assets

# Saving the sample submission in assets directory
test_dataset.to_csv(os.path.join("assets", "submission.csv"), index=False)

# Uploading the Results

In [32]:
!aicrowd notebook submit -c emotion-detection -a assets --no-verify

Mounting Google Drive 💾
Your Google Drive will be mounted to access the colab notebook
Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.activity.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fexperimentsandconfigs%20https%3a%2f%2fwww.googleapis.com%2fauth%2fphotos.native&response_type=code

Enter your authorization code:
4/1AY0e-g5pAPPVY6MNUc2r_h0nM50g-DIq6ktoR1RHlwNZ7rGWbiE57hHYZM8
Mounted at /content/drive
Using notebook: /content/drive/MyDrive/Colab Notebooks/embedding-xgboost-classifier.ipynb for submission...
Scrubbing API keys from the notebook...
Collecting notebook...
submission.zip ━━━━━━━━━━━━━━━━━━ 100.0% • 328.2/326.6 KB • 930.3 kB/s • 0:00:00
                                                  ╭─────────────────────────╮
                                                  │ Successfully submitted! │
                                                  ╰─────────────────────────╯
                                                        Important links
┌──────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│  This submission │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection/submissions/147021              │
│                  │                                                                                                          │
│  All submissions │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection/submissions?my_submissions=true │
│                  │                                                                                                          │
│      Leaderboard │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection/leaderboards                    │
│                  │                                                                                                          │
│ Discussion forum │ https://discourse.aicrowd.com/c/ai-blitz-9                                                               │
│                  │                                                                                                          │
│   Challenge page │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection                                 │
└──────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────┘