# Downloading Dataset

In [5]:
!pip install aicrowd-cli

Collecting aicrowd-cli
  Downloading aicrowd_cli-0.1.7-py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 5.7 MB/s eta 0:00:011
Collecting rich<11,>=10.0.0
  Downloading rich-10.3.0-py3-none-any.whl (205 kB)
     |████████████████████████████████| 205 kB 6.6 MB/s eta 0:00:01
Collecting tqdm<5,>=4.56.0
  Downloading tqdm-4.61.1-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 4.8 MB/s eta 0:00:01
Collecting toml<1,>=0.10.2
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting gitpython<4,>=3.1.12
  Downloading GitPython-3.1.17-py3-none-any.whl (166 kB)
     |████████████████████████████████| 166 kB 5.0 MB/s eta 0:00:01
Requirement already satisfied: click<8,>=7.1.2 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from aicrowd-cli) (7.1.2)
Collecting requests<3,>=2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting requests-toolbelt<1,>=0.9.1
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 6.8 MB/s  eta 0:00:01
Collecting typing-extensions>=3.7.4.0
  Downloading typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.7-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 7.0 MB/s  eta 0:00:01
Collecting smmap<5,>=3.0.1
  Downloading smmap-4.0.0-py2.py3-none-any.whl (24 kB)
Requirement already satisfied: certifi>=2017.4.17 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from requests<3,>=2.25.1->aicrowd-cli) (2017.7.27.1)
Requirement already satisfied: idna<3,>=2.5 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from requests<3,>=2.25.1->aicrowd-cli) (2.6)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from requests<3,>=2.25.1->aicrowd-cli) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from requests<3,>=2.25.1->aicrowd-cli) (1.22)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from rich<11,>=10.0.0->aicrowd-cli) (2.6.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from rich<11,>=10.0.0->aicrowd-cli) (0.4.3)
Collecting dataclasses<0.9,>=0.7
  Using cached dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 9.7 MB/s  eta 0:00:01
Installing collected packages: smmap, typing-extensions, requests, gitdb, dataclasses, commonmark, tqdm, toml, rich, requests-toolbelt, gitpython, aicrowd-cli
  Attempting uninstall: requests
    Found existing installation: requests 2.24.0
    Uninstalling requests-2.24.0:
      Successfully uninstalled requests-2.24.0
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.42.0
    Uninstalling tqdm-4.42.0:
      Successfully uninstalled tqdm-4.42.0
  Attempting uninstall: toml
    Found existing installation: toml 0.10.1
    Uninstalling toml-0.10.1:
      Successfully uninstalled toml-0.10.1
Successfully installed aicrowd-cli-0.1.7 commonmark-0.9.1 dataclasses-0.8 gitdb-4.0.7 gitpython-3.1.17 requests-2.25.1 requests-toolbelt-0.9.1 rich-10.3.0 smmap-4.0.0 toml-0.10.2 tqdm-4.61.1 typing-extensions-3.10.0.0

In [6]:
API_KEY = 'cc0a3da7611cfc6098a7bd9db11b3ecf' # Please get your your API Key from [https://www.aicrowd.com/participants/me]
!aicrowd login --api-key $API_KEY

API Key valid
Saved API Key successfully!

In [7]:
# Downloading the Dataset
!mkdir data
!aicrowd dataset download --challenge emotion-detection -j 3 -o data

test.csv:   0%|                                      | 0.00/642k [00:00<?, ?B/s]
val.csv:   0%|                                       | 0.00/262k [00:00<?, ?B/s]

train.csv:   0%|                                    | 0.00/2.30M [00:00<?, ?B/s]
val.csv: 100%|████████████████████████████████| 262k/262k [00:00<00:00, 392kB/s]
test.csv: 100%|███████████████████████████████| 642k/642k [00:00<00:00, 676kB/s]


train.csv:  46%|████████████▊               | 1.05M/2.30M [00:01<00:01, 868kB/s]

train.csv: 100%|███████████████████████████| 2.30M/2.30M [00:01<00:00, 1.46MB/s]

# Downloading & Importing Libraries

In [1]:
!pip install --upgrade spacy rich
!python -m spacy download en_core_web_sm # Downloaing the model for engligh language will contains many pretrained preprocessing pipelines

Collecting spacy
  Downloading spacy-3.0.6-cp36-cp36m-macosx_10_9_x86_64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 5.3 MB/s eta 0:00:01
Requirement already satisfied: rich in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (10.3.0)
Collecting cymem<2.1.0,>=2.0.2
  Downloading cymem-2.0.5-cp36-cp36m-macosx_10_9_x86_64.whl (32 kB)
Collecting pydantic<1.8.0,>=1.7.1
  Downloading pydantic-1.7.4-cp36-cp36m-macosx_10_9_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 16.3 MB/s eta 0:00:01
Requirement already satisfied: typing-extensions<4.0.0.0,>=3.7.4 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy) (3.10.0.0)
Collecting blis<0.8.0,>=0.4.0
  Downloading blis-0.7.4-cp36-cp36m-macosx_10_9_x86_64.whl (5.8 MB)
     |████████████████████████████████| 5.8 MB 7.9 MB/s eta 0:00:01
Requirement already satisfied: setuptools in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy) (50.3.0)
Collecting thinc<8.1.0,>=8.0.3
  Downloading thinc-8.0.4-cp36-cp36m-macosx_10_9_x86_64.whl (591 kB)
     |████████████████████████████████| 591 kB 11.7 MB/s eta 0:00:01
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy) (4.61.1)
Requirement already satisfied: numpy>=1.15.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy) (1.18.5)
Collecting pathy>=0.3.5
  Downloading pathy-0.5.2-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 4.8 MB/s  eta 0:00:01
Collecting wasabi<1.1.0,>=0.8.1
  Downloading wasabi-0.8.2-py3-none-any.whl (23 kB)
Collecting srsly<3.0.0,>=2.4.1
  Downloading srsly-2.4.1-cp36-cp36m-macosx_10_9_x86_64.whl (449 kB)
     |████████████████████████████████| 449 kB 21.8 MB/s eta 0:00:01
Collecting preshed<3.1.0,>=3.0.2
  Downloading preshed-3.0.5-cp36-cp36m-macosx_10_9_x86_64.whl (106 kB)
     |████████████████████████████████| 106 kB 19.7 MB/s eta 0:00:01
Requirement already satisfied: jinja2 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy) (2.11.2)
Requirement already satisfied: packaging>=20.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy) (20.4)
Collecting catalogue<2.1.0,>=2.0.3
  Downloading catalogue-2.0.4-py3-none-any.whl (16 kB)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy) (2.25.1)
Collecting typer<0.4.0,>=0.3.0
  Downloading typer-0.3.2-py3-none-any.whl (21 kB)
Collecting spacy-legacy<3.1.0,>=3.0.4
  Downloading spacy_legacy-3.0.6-py2.py3-none-any.whl (12 kB)
Collecting murmurhash<1.1.0,>=0.28.0
  Downloading murmurhash-1.0.5-cp36-cp36m-macosx_10_9_x86_64.whl (18 kB)
Requirement already satisfied: zipp>=0.5 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from catalogue<2.1.0,>=2.0.3->spacy) (3.1.0)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from packaging>=20.0->spacy) (2.4.7)
Requirement already satisfied: six in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from packaging>=20.0->spacy) (1.15.0)
Collecting smart-open<4.0.0,>=2.2.0
  Using cached smart_open-3.0.0-py3-none-any.whl
Requirement already satisfied: dataclasses<1.0,>=0.6 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from pathy>=0.3.5->spacy) (0.8)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2017.7.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.22)
Requirement already satisfied: idna<3,>=2.5 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6)
Collecting contextvars<3,>=2.4
  Using cached contextvars-2.4-py3-none-any.whl
Collecting immutables>=0.9
  Using cached immutables-0.15-cp36-cp36m-macosx_10_14_x86_64.whl (53 kB)
Requirement already satisfied: click<7.2.0,>=7.1.1 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from typer<0.4.0,>=0.3.0->spacy) (7.1.2)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from rich) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from rich) (2.6.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from rich) (0.4.3)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from jinja2->spacy) (1.1.1)
Installing collected packages: murmurhash, immutables, cymem, catalogue, wasabi, typer, srsly, smart-open, pydantic, preshed, contextvars, blis, thinc, spacy-legacy, pathy, spacy
  Attempting uninstall: smart-open
    Found existing installation: smart-open 2.0.0
    Uninstalling smart-open-2.0.0:
      Successfully uninstalled smart-open-2.0.0
Successfully installed blis-0.7.4 catalogue-2.0.4 contextvars-2.4 cymem-2.0.5 immutables-0.15 murmurhash-1.0.5 pathy-0.5.2 preshed-3.0.5 pydantic-1.7.4 smart-open-3.0.0 spacy-3.0.6 spacy-legacy-3.0.6 srsly-2.4.1 thinc-8.0.4 typer-0.3.2 wasabi-0.8.2
Collecting en-core-web-sm==3.0.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0-py3-none-any.whl (13.7 MB)
     |████████████████████████████████| 13.7 MB 9.2 MB/s eta 0:00:01
Requirement already satisfied: spacy<3.1.0,>=3.0.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from en-core-web-sm==3.0.0) (3.0.6)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (3.0.5)
Requirement already satisfied: numpy>=1.15.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (1.18.5)
Requirement already satisfied: pydantic<1.8.0,>=1.7.1 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (1.7.4)
Requirement already satisfied: typing-extensions<4.0.0.0,>=3.7.4 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (3.10.0.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.0.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.4 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (3.0.6)
Requirement already satisfied: thinc<8.1.0,>=8.0.3 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (8.0.4)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (4.61.1)
Requirement already satisfied: setuptools in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (50.3.0)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (0.7.4)
Requirement already satisfied: pathy>=0.3.5 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (0.5.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.25.1)
Requirement already satisfied: typer<0.4.0,>=0.3.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (0.3.2)
Requirement already satisfied: jinja2 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.11.2)
Requirement already satisfied: wasabi<1.1.0,>=0.8.1 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (0.8.2)
Requirement already satisfied: packaging>=20.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (20.4)
Requirement already satisfied: catalogue<2.1.0,>=2.0.3 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (1.0.5)
Requirement already satisfied: srsly<3.0.0,>=2.4.1 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.4.1)
Requirement already satisfied: zipp>=0.5 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from catalogue<2.1.0,>=2.0.3->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (3.1.0)
Requirement already satisfied: six in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from packaging>=20.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (1.15.0)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from packaging>=20.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.4.7)
Requirement already satisfied: dataclasses<1.0,>=0.6 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from pathy>=0.3.5->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (0.8)
Requirement already satisfied: smart-open<4.0.0,>=2.2.0 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from pathy>=0.3.5->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (3.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (1.22)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2017.7.27.1)
Requirement already satisfied: idna<3,>=2.5 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.6)
Requirement already satisfied: contextvars<3,>=2.4 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from thinc<8.1.0,>=8.0.3->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (2.4)
Requirement already satisfied: immutables>=0.9 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from contextvars<3,>=2.4->thinc<8.1.0,>=8.0.3->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (0.15)
Requirement already satisfied: click<7.2.0,>=7.1.1 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from typer<0.4.0,>=0.3.0->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/administrator/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages (from jinja2->spacy<3.1.0,>=3.0.0->en-core-web-sm==3.0.0) (1.1.1)
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.0.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [5]:
!curl https://raw.githubusercontent.com/tylerneylon/explacy/master/explacy.py -o explacy.py

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6896  100  6896    0     0   164k      0 --:--:-- --:--:-- --:--:--  164k

In [6]:
import time
import pandas as pd
import spacy
import explacy
import random
from sklearn import tree
from sklearn.metrics import f1_score, accuracy_score
import os

# To make things more beautiful! 
from rich.console import Console
from rich.table import Table
from rich import pretty
pretty.install()


# Seeding everything for getting same results 
random.seed(1)
spacy.util.fix_random_seed(1)

In [7]:
# spaCy v3.0 the the latest version spaCy 
spacy.__version__

'3.0.6'

# Reading Dataset

In [8]:
train_dataset = pd.read_csv("data/train.csv")
validation_dataset = pd.read_csv("data/val.csv")[1:]
test_dataset = pd.read_csv("data/test.csv")
train_dataset.head(20)

,text,label
0,takes no time to copy/paste a press release,0
1,You're delusional,1
2,Jazz fan here. I completely feel. Lindsay Mann...,0
3,ah i was also confused but i think they mean f...,0
4,Thank you so much. ♥️ that means a lot.,0
5,And I’ll be there!!!,0
6,There are some amazingly cringey compilations ...,0
7,Check the frame (FPS) limit option in the adva...,0
8,you made me think I was in the dbd subreddit w...,0
9,It was in your op.,0
10,There is a reason 15 people liked my comment d...,0
11,"He's not THAT bad on YouTube, but on Twitter.....",0
12,As someone who is dairy intolerant (milk is in...,0
13,IVE NEVER BEEN MORE PROUD TO CAMPAIGN FOR A CA...,0
14,See him live if you haven’t already. One of my...,0
15,CNN has video of the arrest. Someone needs to ...,0
16,"It wasn't fair on the rest of the list, nothin...",1
17,Finally got this in the mail today. I'm pretty...,0
18,"Yes, once I even deleted my account because I ...",1
19,This is truly the most captivating trilogy I’v...,0

In [18]:
train_dataset['label'].value_counts()

# Text Classification

In [9]:
nlp = spacy.load('en_core_web_sm')

In [10]:
# Getting a sample text from training dataset to demonstrate word2vec  
sample_text = train_dataset.iloc[2]['text'] 
sample_text

"Jazz fan here. I completely feel. Lindsay Mann cousins has more votes than Lindsay Mann, and Lindsay Mann hasn't even stepped on the court this year"

In [11]:
# Inputting the text in nlp function
doc = nlp(sample_text)

# Getting the embeddings from the sample text
doc.vector

array([ 0.5871044 ,  0.10283045,  0.23638554, -0.08171239,  0.02029083,
       -0.12000011, -0.1948305 ,  0.1250714 , -0.01082261, -0.34358275,
       -0.16639529, -0.04950966, -0.01394221,  0.06337869, -0.30135745,
        0.22211872, -0.17156254,  0.03178046,  0.30427024, -0.10826215,
       -0.25342506,  0.30617625, -0.17000276,  0.35598457, -0.00835321,
       -0.11478721, -0.1430562 ,  0.02518663,  0.60922873,  0.19284171,
       -0.23238468, -0.27463096, -0.13183063, -0.27534658,  0.25664884,
        0.05174499,  0.18620381,  0.11441176, -0.10955156,  0.29338667,
       -0.15877348, -0.02914245,  0.1963947 , -0.04410601,  0.12061837,
       -0.0941467 ,  0.27903876, -0.09223508, -0.00497099, -0.25587952,
        0.21098505,  0.01725493, -0.29827487,  0.0894304 ,  0.14340732,
       -0.0376591 , -0.3396481 ,  0.19914041,  0.28556582,  0.18212257,
        0.5140986 ,  0.02056837, -0.18578346, -0.28987882, -0.16651031,
       -0.10539112, -0.05578137,  0.00634063,  0.02737209,  0.14916842,
        0.15076284,  0.31409967, -0.06142968, -0.13555318, -0.08603293,
        0.40901124, -0.07265005, -0.19719984, -0.349496  ,  0.11685906,
        0.20542377,  0.1133521 ,  0.13061962,  0.2739835 , -0.00384022,
       -0.21771309, -0.28375924, -0.41814512, -0.42588463, -0.06813539,
       -0.27145588,  0.17521115, -0.15065633, -0.05529505,  0.06760314,
       -0.1013436 ], dtype=float32)

# Creating our Dataset

In [12]:
def create_data(dataset, is_train=True):

  # If we are using a training dataset
  if is_train == True:

    # Getting all text into a python list
    texts = list(dataset['text'].values)
                 
    # Put the list into the nlp pipeline and converting the output into a list
    preprocessed_texts = list(nlp.pipe(texts))

    # Getting vectors for all texts 
    X = [string.vector  for string in preprocessed_texts]

    # Labels for the corrosponding texts 
    y = dataset['label'].tolist()

    return X, y

  else:

    # Getting all text into a python list
    texts = list(dataset['text'].values)
                 
    # Put the list into the nlp pipeline and converting the output into a list
    preprocessed_texts = list(nlp.pipe(texts))

    # Getting vectors for all texts 
    X = [string.vector  for string in preprocessed_texts]

    return X

In [15]:
# Creating the training dataset
start_time = time.time()
X_train, y_train = create_data(train_dataset)
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

# Creating the validation dataset
start_time = time.time()
X_val, y_val = create_data(validation_dataset)
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

X_train[0], y_train[0]

Elapsed time: 47.9502 seconds
Elapsed time: 5.5723 seconds

(
    array([ 0.14151856, -0.05933758, -0.08044346, -0.1107378 ,  0.11325426,
        0.15893325, -0.44572473,  0.21314225,  0.07863858, -0.12423076,
        0.08870672, -0.16083065,  0.03217425, -0.18913928, -0.43932933,
        0.614143  , -0.04348904,  0.15507331, -0.10762676, -0.6841317 ,
       -0.52705824,  0.19307005,  0.5150874 , -0.78364027, -0.5798768 ,
       -0.36855024,  0.261396  ,  0.08007441,  0.13464396, -0.11683945,
       -0.40335947, -0.4810744 , -0.1996509 , -0.40538788,  0.907061  ,
       -0.08425845,  0.41184407, -0.05256712, -0.01928839,  0.67991185,
        0.18288395, -0.00932413,  0.15208176,  0.5218999 , -0.21960959,
       -0.0870916 ,  0.0571377 ,  0.39526838,  0.11505216,  0.03575191,
        0.18940884,  0.35989684, -0.03341857,  0.50211823,  0.25563306,
       -0.45388022,  0.04130013,  0.1111506 ,  0.11391255,  0.12924205,
       -0.44648582, -0.04701398, -0.12538372,  0.11663225,  0.3620197 ,
       -0.00661604, -0.25024778, -0.3998903 , -0.07583453,  0.747198  ,
        0.5959583 , -0.17592818, -0.04306039, -0.52941674, -0.12472894,
       -0.43728942, -0.06499843,  0.0685156 ,  0.23714057, -0.20262413,
        0.41856593,  0.01466806, -0.19088936,  0.36778176,  0.09763627,
       -0.3632294 , -0.15831968, -0.43174067, -0.08282916, -0.09869532,
        0.14616643,  0.02205803, -0.33136448,  0.19892709, -0.50562334,
       -0.14163868], dtype=float32),
    0
)

# Creating the Model

In [19]:
clf = tree.DecisionTreeClassifier()

# Training

In [20]:
start_time = time.time()
clf = clf.fit(X_train, y_train)
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

clf

Elapsed time: 4.7165 seconds

DecisionTreeClassifier()

# Validation

In [21]:
y_pred = clf.predict(X_val)

# Getting F1 & Accuracy score of validation predictions
f1 = f1_score(y_val, y_pred)
accuracy = accuracy_score(y_val, y_pred)

print(f"Validation F1 Score  : {round(f1, 4)} and Accuracy Score {round(accuracy, 4)}")

Validation F1 Score  : 0.2493 and Accuracy Score 0.6757

# Submitting Results

In [22]:
# By settings is_train=False, the create_data function will only output the features as setuped in the function

start_time = time.time()
test_data = create_data(test_dataset, is_train=False)

test_predictions = clf.predict(test_data)
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

Elapsed time: 15.7579 seconds

In [23]:
# Applying the predictions to the labels column of the sample submission 
test_dataset['label'] = test_predictions
print(test_dataset.shape)

test_dataset.head(20)

(8682, 2)

,text,label
0,I was already over the edge with Cassie Zamora...,0
1,I think you're right. She has oodles of cash a...,1
2,Haha I love this. I used to give mine phone bo...,0
3,Probably out of desperation as they going no a...,1
4,Sorry !! You’re real good at that!!,0
5,I say we get the pitch forks and make him have...,0
6,He looks really different now.,1
7,I swear people just want to be angry,0
8,lol robot car,0
9,Yeah I’ve been watching these videos and they ...,1
10,Stranger things have happened.,0
11,No you pick a different hero. Aint fkn rocket ...,0
12,Was this tattoo designed by Desiree Erickson?,0
13,Not unexpected this election was gonna be a br...,0
14,Come to Nashville. Love to help with that prob...,0
15,they're a bit expensive anyways,0
16,"No, it isn't K.",1
17,Wow! It's dead af here,0
18,Thankyou! Good luck with your search! An AP is...,0
19,This spoke to my soul. I might cry 😭. I really...,1

In [24]:
!mkdir assets

# Saving the sample submission in assets directory
test_dataset.to_csv(os.path.join("assets", "submission.csv"), index=False)

# Uploading the Results

In [25]:
!aicrowd notebook submit -c emotion-detection -a assets --no-verify

WARNING: Got more than 1 jupyter server, selecting the latest session
WARNING: Got more than 1 jupyter server, selecting the latest session
Using notebook: /Users/administrator/Desktop/shenghao-repos/aicrowd-emotion-detection/starter-code.ipynb for submission...
WARNING: Got more than 1 jupyter server, selecting the latest session
WARNING: Got more than 1 jupyter server, selecting the latest session
Scrubbing API keys from the notebook...
Collecting notebook...
WARNING: Got more than 1 jupyter server, selecting the latest session
submission.zip ━━━━━━━━━━━━━━━━━━━ 100.0% • 306.9/305.3 KB • 40.4 kB/s • 0:00:00[0m • 0:00:01[36m0:00:01
                                                  ╭─────────────────────────╮
                                                  │ Successfully submitted! │
                                                  ╰─────────────────────────╯
                                                        Important links
┌──────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│  This submission │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection/submissions/146707              │
│                  │                                                                                                          │
│  All submissions │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection/submissions?my_submissions=true │
│                  │                                                                                                          │
│      Leaderboard │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection/leaderboards                    │
│                  │                                                                                                          │
│ Discussion forum │ https://discourse.aicrowd.com/c/ai-blitz-9                                                               │
│                  │                                                                                                          │
│   Challenge page │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection                                 │
└──────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────┘