# Download Dataset

In [1]:
!pip install aicrowd-cli

Requirement already satisfied: aicrowd-cli in /usr/local/lib/python3.7/dist-packages (0.1.7)
Requirement already satisfied: rich<11,>=10.0.0 in /usr/local/lib/python3.7/dist-packages (from aicrowd-cli) (10.4.0)
Requirement already satisfied: gitpython<4,>=3.1.12 in /usr/local/lib/python3.7/dist-packages (from aicrowd-cli) (3.1.18)
Requirement already satisfied: toml<1,>=0.10.2 in /usr/local/lib/python3.7/dist-packages (from aicrowd-cli) (0.10.2)
Requirement already satisfied: click<8,>=7.1.2 in /usr/local/lib/python3.7/dist-packages (from aicrowd-cli) (7.1.2)
Requirement already satisfied: requests<3,>=2.25.1 in /usr/local/lib/python3.7/dist-packages (from aicrowd-cli) (2.25.1)
Requirement already satisfied: tqdm<5,>=4.56.0 in /usr/local/lib/python3.7/dist-packages (from aicrowd-cli) (4.61.1)
Requirement already satisfied: requests-toolbelt<1,>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from aicrowd-cli) (0.9.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from rich<11,>=10.0.0->aicrowd-cli) (0.4.4)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /usr/local/lib/python3.7/dist-packages (from rich<11,>=10.0.0->aicrowd-cli) (0.9.1)
Requirement already satisfied: typing-extensions<4.0.0,>=3.7.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from rich<11,>=10.0.0->aicrowd-cli) (3.7.4.3)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /usr/local/lib/python3.7/dist-packages (from rich<11,>=10.0.0->aicrowd-cli) (2.6.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.7/dist-packages (from gitpython<4,>=3.1.12->aicrowd-cli) (4.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.25.1->aicrowd-cli) (2021.5.30)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.25.1->aicrowd-cli) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.25.1->aicrowd-cli) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.25.1->aicrowd-cli) (1.24.3)
Requirement already satisfied: smmap<5,>=3.0.1 in /usr/local/lib/python3.7/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.12->aicrowd-cli) (4.0.0)

In [2]:
API_KEY = 'cc0a3da7611cfc6098a7bd9db11b3ecf' # Please get your your API Key from [https://www.aicrowd.com/participants/me]
!aicrowd login --api-key $API_KEY

API Key valid
Saved API Key successfully!

In [3]:
# Downloading the Dataset
!mkdir data
!aicrowd dataset download --challenge emotion-detection -j 3 -o data

mkdir: cannot create directory ‘data’: File exists
val.csv:   0% 0.00/262k [00:00<?, ?B/s]

train.csv:   0% 0.00/2.30M [00:00<?, ?B/s]
val.csv: 100% 262k/262k [00:00<00:00, 1.50MB/s]

test.csv: 100% 642k/642k [00:00<00:00, 2.77MB/s]


train.csv: 100% 2.30M/2.30M [00:00<00:00, 7.18MB/s]

# Download & Import Libraries

In [4]:
!pip install emoji

Requirement already satisfied: emoji in /usr/local/lib/python3.7/dist-packages (1.2.0)

In [5]:
import os
import re
import emoji
import time
import numpy as np
import pandas as pd
import nltk
import torch
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import f1_score, accuracy_score
from torch import nn, optim, FloatTensor
from torch.utils.data import Dataset, DataLoader
from copy import deepcopy

In [6]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

# Read Dataset

In [7]:
train_dataset = pd.read_csv("data/train.csv")
validation_dataset = pd.read_csv("data/val.csv")[1:]
test_dataset = pd.read_csv("data/test.csv")

train_dataset.head(20)

                                                 text  label
0         takes no time to copy/paste a press release      0
1                                   You're delusional      1
2   Jazz fan here. I completely feel. Lindsay Mann...      0
3   ah i was also confused but i think they mean f...      0
4             Thank you so much. ♥️ that means a lot.      0
5                                And I’ll be there!!!      0
6   There are some amazingly cringey compilations ...      0
7   Check the frame (FPS) limit option in the adva...      0
8   you made me think I was in the dbd subreddit w...      0
9                                  It was in your op.      0
10  There is a reason 15 people liked my comment d...      0
11  He's not THAT bad on YouTube, but on Twitter.....      0
12  As someone who is dairy intolerant (milk is in...      0
13  IVE NEVER BEEN MORE PROUD TO CAMPAIGN FOR A CA...      0
14  See him live if you haven’t already. One of my...      0
15  CNN has video of the arrest. Someone needs to ...      0
16  It wasn't fair on the rest of the list, nothin...      1
17  Finally got this in the mail today. I'm pretty...      0
18  Yes, once I even deleted my account because I ...      1
19  This is truly the most captivating trilogy I’v...      0

# Process text

In [8]:
stops = set(stopwords.words('english'))
porter = nltk.PorterStemmer()

def pre_process(str):
    def rm_html_tags(str):
        html_prog = re.compile(r'<[^>]+>',re.S)
        return html_prog.sub('', str)

    def rm_html_escape_characters(str):
        pattern_str = r'&quot;|&amp;|&lt;|&gt;|&nbsp;|&#34;|&#38;|&#60;|&#62;|&#160;|&#20284;|&#30524;|&#26684|&#43;|&#20540|&#23612;'
        escape_characters_prog = re.compile(pattern_str, re.S)
        return escape_characters_prog.sub('', str)

    def rm_at_user(str):
        return re.sub(r'@[a-zA-Z_0-9]*', '', str)

    def rm_url(str):
        return re.sub(r'http[s]?:[/+]?[a-zA-Z0-9_\.\/]*', '', str)

    def rm_repeat_chars(str):
        return re.sub(r'(.)(\1){2,}', r'\1\1', str)

    def rm_hashtag_symbol(str):
        return re.sub(r'#', '', str)

    def rm_time(str):
        return re.sub(r'[0-9][0-9]:[0-9][0-9]', '', str)

    def rm_punctuation(str):
        return re.sub(r'[^\w\s]', ' ', str)

    def split_emojis(str):
        text_part = ''.join(c for c in str if c not in emoji.UNICODE_EMOJI)
        emoji_part = ' '.join(c for c in str if c in emoji.UNICODE_EMOJI)
        return text_part + ' ' + emoji_part
    
    # do not change the preprocessing order only if you know what you're doing 
    str = str.lower()
    str = rm_url(str)        
    str = rm_at_user(str)        
    str = rm_repeat_chars(str) 
    str = rm_hashtag_symbol(str)       
    str = rm_time(str)
    str = rm_punctuation(str)
    # str = emoji.demojize(str, delimiters=(' emoji_', ' '))
    str = split_emojis(str)

    try:
        str = nltk.tokenize.word_tokenize(str)
        try:
            str = [porter.stem(t) for t in str]
        except:
            pass
    except:
        pass

    words = [w for w in str if w and w not in stops]
    return ' '.join(words)

In [9]:
text = "takes no time to copy/paste a press release"
pre_process(text)

'take time copi past press releas'

In [10]:
start_time = time.time()
train_dataset['processed_text'] = train_dataset['text'].apply(
    lambda x: pre_process(x)
)
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

train_dataset.head(20)

Elapsed time: 14.1132 seconds

                                                 text  ...                                     processed_text
0         takes no time to copy/paste a press release  ...                   take time copi past press releas
1                                   You're delusional  ...                                           delusion
2   Jazz fan here. I completely feel. Lindsay Mann...  ...  jazz fan complet feel lindsay mann cousin ha v...
3   ah i was also confused but i think they mean f...  ...     ah wa also confus think mean friend around age
4             Thank you so much. ♥️ that means a lot.  ...                                thank much mean lot
5                                And I’ll be there!!!  ...
6   There are some amazingly cringey compilations ...  ...  amazingli cringey compil terribl dialogu thi s...
7   Check the frame (FPS) limit option in the adva...  ...  check frame fp limit option advanc graphic opt...
8   you made me think I was in the dbd subreddit w...  ...      made think wa dbd subreddit statement idk whi
9                                  It was in your op.  ...                                              wa op
10  There is a reason 15 people liked my comment d...  ...  reason 15 peopl like comment dear fifteen peop...
11  He's not THAT bad on YouTube, but on Twitter.....  ...               bad youtub twitter let say problemat
12  As someone who is dairy intolerant (milk is in...  ...  someon dairi intoler milk _everyth _ thi vegan...
13  IVE NEVER BEEN MORE PROUD TO CAMPAIGN FOR A CA...  ...  ive never proud campaign candid stg im happi c...
14  See him live if you haven’t already. One of my...  ...           see live alreadi one favorit see concert
15  CNN has video of the arrest. Someone needs to ...  ...      cnn ha video arrest someon need put cop theme
16  It wasn't fair on the rest of the list, nothin...  ...                fair rest list noth good tim horton
17  Finally got this in the mail today. I'm pretty...  ...  final got thi mail today pretti excit favorit ...
18  Yes, once I even deleted my account because I ...  ...  ye onc even delet account becaus wa nervou vot...
19  This is truly the most captivating trilogy I’v...  ...  thi truli captiv trilog ever read eager read t...

[20 rows x 3 columns]

In [11]:
start_time = time.time()
validation_dataset['processed_text'] = validation_dataset['text'].apply(
    lambda x: pre_process(x)
)
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

validation_dataset.head(20)

Elapsed time: 1.6528 seconds

                                                 text  ...                                     processed_text
1                                   im still starving  ...                                     im still starv
2   *Hey just noticed..* it's your **2nd Cakeday**...  ...               hey notic 2nd cakeday slumbishop hug
3           They just did. Check out the sticky post.  ...                                  check sticki post
4                     I hope so too, she deserves it.  ...                                        hope deserv
5   is it dangerous to take a quick photo while st...  ...             danger take quick photo stop red light
6   I’m in my second year. Still closeted. Still u...  ...  second year still closet still uncomfort bodi ...
7                  Noted, I've been looking into that  ...                                          note look
8   Thank you for saying that I just haven’t felt ...  ...                thank say felt right sad constantli
9   Screw the watch stuff, I wanna hear about the ...  ...                 screw watch stuff wan na hear porn
10  Exactly....we need a car tunnel, and then let ...  ...  exactli need car tunnel let old road allow tru...
11  Also, lay a piece of tp down BEFORE you drop y...  ...  also lay piec tp befor drop first deuc noth le...
12  Go out of your way to listen to the opening se...  ...  go way listen open segment russel wise show to...
13  It's crisp, no filler material. Interesting pr...  ...  crisp filler materi interest protagonist amaz ...
14  Im not looking to be forgiven lol. I still sta...  ...  im look forgiven lol still stand said pll onli...
15  So what should I do?? I’ve been dating her for...  ...                  date eight year confus pleas help
16  Was it? I thought it was someone from last sea...  ...  wa thought wa someon last season mayb rememb w...
17  Is it a radical opinion to say no two consenti...  ...   radic opinion say two consent adult abl kill lol
18  Yes, absolutely. "But woe to the one who betra...  ...  ye absolut woe one betray would better man nev...
19  She was acting from her emotions instead of lo...  ...      wa act emot instead logic suppos huge distain
20              Omg I just finished and I'm in awe...  ...                                     omg finish awe

[20 rows x 3 columns]

# Create TF-IDF Features

In [12]:
print(train_dataset.shape)
print(validation_dataset.shape)
combined_dataset = pd.concat([train_dataset, validation_dataset])
print(combined_dataset.shape)

(31255, 3)
(3472, 3)
(34727, 3)

In [13]:
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=5000)
tfidf_vect.fit(combined_dataset['processed_text'])

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=5000,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='\\w{1,}', tokenizer=None,
                use_idf=True, vocabulary=None)

In [14]:
start_time = time.time()
xtrain_tfidf =  tfidf_vect.transform(train_dataset['processed_text'])
xval_tfidf =  tfidf_vect.transform(validation_dataset['processed_text'])
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

print(xtrain_tfidf.shape)
print(xval_tfidf.shape)

Elapsed time: 0.3386 seconds
(31255, 5000)
(3472, 5000)

# Transform Data

In [15]:
class trainData(Dataset):
    def __init__(self, X_data, y_data):
        self.X_data = X_data
        self.y_data = y_data
        
    def __getitem__(self, index):
        return self.X_data[index], self.y_data[index]
        
    def __len__ (self):
        return len(self.X_data)

## test data    
class testData(Dataset):
    def __init__(self, X_data):
        self.X_data = X_data
        
    def __getitem__(self, index):
        return self.X_data[index]
        
    def __len__ (self):
        return len(self.X_data)

In [16]:
y_train = train_dataset['label'].values
y_val = validation_dataset['label'].values

train_data = trainData(
    FloatTensor(xtrain_tfidf.toarray()), 
    FloatTensor(y_train)
)
val_data = trainData(
    FloatTensor(xval_tfidf.toarray()), 
    FloatTensor(y_val)
)

In [17]:
## Initialize dataloader
LEARNING_RATE = 0.001
BATCH_SIZE = 128
NUM_EPOCHS = 100

train_loader = DataLoader(dataset=train_data, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(dataset=val_data, batch_size=BATCH_SIZE)

# Train Model

In [18]:
train_dataset['label'].value_counts()

0    24718
1     6537
Name: label, dtype: int64

In [19]:
# del model

In [20]:
# Hyperparameters for our network
input_size = xtrain_tfidf.shape[1]
# hidden_sizes = [64, 32]
hidden_sizes = [128, 64]
output_size = 1

# Build a feed-forward network
def declare_model():
    return nn.Sequential(
        nn.Linear(input_size, hidden_sizes[0]),
        nn.Dropout(0.5),
        nn.BatchNorm1d(hidden_sizes[0]),
        nn.ReLU(),
        nn.Linear(hidden_sizes[0], hidden_sizes[1]),
        nn.Dropout(0.5),
        nn.BatchNorm1d(hidden_sizes[1]),
        nn.ReLU(),
        nn.Linear(hidden_sizes[1], output_size),
        nn.Sigmoid()
    )

model = declare_model()
print(model)

Sequential(
  (0): Linear(in_features=5000, out_features=128, bias=True)
  (1): Dropout(p=0.5, inplace=False)
  (2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (3): ReLU()
  (4): Linear(in_features=128, out_features=64, bias=True)
  (5): Dropout(p=0.5, inplace=False)
  (6): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (7): ReLU()
  (8): Linear(in_features=64, out_features=1, bias=True)
  (9): Sigmoid()
)

In [21]:
# Declare class weight
criterion = nn.BCEWithLogitsLoss(pos_weight = torch.FloatTensor ([4.0]))
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

In [22]:
def eval(y_pred, y_true):
    y_pred_tag = torch.round(torch.sigmoid(y_pred))
    tp = (y_true * y_pred).sum().to(torch.float32)
    tn = ((1 - y_true) * (1 - y_pred)).sum().to(torch.float32)
    fp = ((1 - y_true) * y_pred).sum().to(torch.float32)
    fn = (y_true * (1 - y_pred)).sum().to(torch.float32)
    
    epsilon = 1e-7
    precision = tp / (tp + fp + epsilon)
    recall = tp / (tp + fn + epsilon)
    f1 = 2 * (precision*recall) / (precision + recall + epsilon)
    acc = (tp + tn) / (tp + tn + fp + fn)
    
    return f1, acc

In [23]:
N_EPOCHS_STOP = 6
min_val_loss = np.Inf
epochs_no_improve = 0
best_model_state = {}

for e in range(1, NUM_EPOCHS+1):
    train_loss = val_loss = 0
    train_acc = val_acc = 0
    train_f1 = val_f1 = 0
    for X_batch, y_batch in train_loader:
        # X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()        
        y_pred = model(X_batch)
        loss = criterion(y_pred, y_batch.unsqueeze(1))
        f1, acc = eval(y_pred, y_batch.unsqueeze(1))
        
        loss.backward() # Calculate gradients
        optimizer.step() # Update parameters
        
        train_loss += loss.item()
        train_acc += acc
        train_f1 += f1

    for X_batch, y_batch in val_loader:
        y_pred = model(X_batch)
        loss = criterion(y_pred, y_batch.unsqueeze(1))
        f1, acc = eval(y_pred, y_batch.unsqueeze(1))
        val_loss += loss.item()
        val_acc += acc
        val_f1 += f1

    print(
        f'Epoch {e+0:03}: | \
        Training Loss: {train_loss/len(train_loader):.3f} | \
        F1 Score: {train_f1/len(train_loader):.3f} | \
        Acc: {train_acc/len(train_loader):.3f}  | \
        Validation Loss: {val_loss/len(val_loader):.3f} | \
        F1 Score: {val_f1/len(val_loader):.3f} | \
        Acc: {val_acc/len(val_loader):.3f}'
    )

    # Early stopping
    if val_loss/len(val_loader) < min_val_loss:
        # torch.save(model)  # Save the model
        epochs_no_improve = 0
        min_val_loss = val_loss/len(val_loader)
        best_model_state = deepcopy(model.state_dict())
    else:
        epochs_no_improve += 1
    
    if epochs_no_improve >= N_EPOCHS_STOP:
        break

Epoch 001: |         Training Loss: 1.074 |         F1 Score: 0.391 |         Acc: 0.684  |         Validation Loss: 1.030 |         F1 Score: 0.465 |         Acc: 0.744
Epoch 002: |         Training Loss: 0.990 |         F1 Score: 0.567 |         Acc: 0.794  |         Validation Loss: 1.024 |         F1 Score: 0.486 |         Acc: 0.760
Epoch 003: |         Training Loss: 0.960 |         F1 Score: 0.636 |         Acc: 0.829  |         Validation Loss: 1.029 |         F1 Score: 0.484 |         Acc: 0.757
Epoch 004: |         Training Loss: 0.939 |         F1 Score: 0.681 |         Acc: 0.852  |         Validation Loss: 1.024 |         F1 Score: 0.491 |         Acc: 0.770
Epoch 005: |         Training Loss: 0.927 |         F1 Score: 0.709 |         Acc: 0.867  |         Validation Loss: 1.022 |         F1 Score: 0.501 |         Acc: 0.771
Epoch 006: |         Training Loss: 0.918 |         F1 Score: 0.731 |         Acc: 0.879  |         Validation Loss: 1.024 |         F1 Score: 0.498 |         Acc: 0.767
Epoch 007: |         Training Loss: 0.909 |         F1 Score: 0.752 |         Acc: 0.889  |         Validation Loss: 1.027 |         F1 Score: 0.496 |         Acc: 0.759
Epoch 008: |         Training Loss: 0.901 |         F1 Score: 0.771 |         Acc: 0.898  |         Validation Loss: 1.030 |         F1 Score: 0.482 |         Acc: 0.771
Epoch 009: |         Training Loss: 0.897 |         F1 Score: 0.781 |         Acc: 0.903  |         Validation Loss: 1.030 |         F1 Score: 0.487 |         Acc: 0.771
Epoch 010: |         Training Loss: 0.892 |         F1 Score: 0.795 |         Acc: 0.910  |         Validation Loss: 1.031 |         F1 Score: 0.482 |         Acc: 0.766
Epoch 011: |         Training Loss: 0.889 |         F1 Score: 0.802 |         Acc: 0.914  |         Validation Loss: 1.032 |         F1 Score: 0.483 |         Acc: 0.769

In [24]:
best_model_state

OrderedDict([('0.weight',
              tensor([[ 0.0149,  0.0059, -0.0243,  ...,  0.0129, -0.0189,  0.0284],
                      [ 0.0065, -0.0209, -0.0450,  ...,  0.0029,  0.0047,  0.0005],
                      [-0.0230, -0.0171, -0.0388,  ..., -0.0125,  0.0213, -0.0226],
                      ...,
                      [ 0.0023, -0.0383, -0.0392,  ..., -0.0147,  0.0238,  0.0228],
                      [-0.0309,  0.0171,  0.0064,  ...,  0.0214,  0.0543, -0.0416],
                      [-0.0662, -0.0315, -0.0684,  ..., -0.0039, -0.0357,  0.0088]])),
             ('0.bias',
              tensor([-0.0261, -0.0374,  0.0388, -0.0063, -0.0312, -0.0185, -0.0118,  0.0365,
                      -0.0258, -0.0257, -0.0346, -0.0231,  0.0435, -0.0182, -0.0325, -0.0131,
                      -0.0341, -0.0300,  0.0097, -0.0444, -0.0340, -0.0174, -0.0205, -0.0156,
                      -0.0128, -0.0057, -0.0288, -0.0147, -0.0373,  0.0202, -0.0209,  0.0169,
                       0.0627, -0.0421,  0.0211, -0.0239, -0.0081, -0.0396,  0.0128, -0.0163,
                      -0.0198, -0.0029,  0.0467, -0.0416, -0.0403,  0.0133,  0.0479, -0.0068,
                       0.0589, -0.0411, -0.0392, -0.0107,  0.0387, -0.0099, -0.0013, -0.0206,
                       0.0798,  0.0246,  0.0854, -0.0165, -0.0077, -0.0198,  0.0125,  0.0077,
                       0.0301, -0.0333, -0.0520, -0.0263,  0.0369, -0.0162, -0.0114,  0.0012,
                      -0.0013, -0.0247, -0.0206, -0.0201, -0.0309, -0.0278, -0.0091,  0.0410,
                      -0.0258, -0.0369, -0.0321, -0.0130,  0.0095, -0.0293,  0.0096,  0.0358,
                      -0.0061, -0.0241, -0.0078, -0.0136,  0.0199, -0.0138, -0.0247, -0.0149,
                      -0.0083,  0.0196, -0.0190,  0.0038, -0.0410, -0.0192, -0.0110, -0.0118,
                      -0.0230, -0.0120, -0.0154, -0.0143,  0.0258, -0.0285,  0.0161, -0.0584,
                      -0.0184, -0.0392, -0.0127,  0.0409, -0.0179, -0.0369,  0.0990,  0.0287,
                       0.0908, -0.0279, -0.0228, -0.0279, -0.0471, -0.0074, -0.0019, -0.0091])),
             ('2.weight',
              tensor([0.9110, 0.8639, 0.9820, 0.9645, 0.8672, 1.0615, 0.9219, 0.9990, 0.9949,
                      1.1198, 1.0653, 0.9623, 1.0034, 1.0934, 1.0578, 1.0426, 0.9125, 0.9860,
                      0.9869, 0.9507, 0.9087, 0.9417, 0.9387, 1.0364, 0.9774, 1.0692, 1.0113,
                      1.0242, 1.0352, 1.0085, 0.9669, 0.9919, 0.8760, 0.9646, 0.9709, 0.9783,
                      0.9407, 0.9678, 0.9893, 1.0332, 1.0063, 1.1156, 0.9306, 0.9102, 1.0279,
                      0.9666, 0.9395, 1.0957, 0.9513, 0.9126, 1.0079, 1.1138, 0.9759, 0.9155,
                      1.0350, 0.9172, 0.8322, 0.9893, 0.8215, 1.0311, 1.0387, 0.8988, 1.0040,
                      0.9716, 0.9681, 0.9617, 0.9712, 0.8503, 0.9462, 0.9695, 1.0971, 0.9309,
                      0.9897, 0.9477, 1.0111, 0.9286, 1.0187, 0.9041, 0.9908, 0.9827, 0.9751,
                      0.9271, 0.9709, 0.9083, 1.0011, 0.8626, 0.8209, 0.9677, 1.0958, 0.9667,
                      0.9955, 0.9069, 0.9698, 1.0351, 1.0736, 0.9171, 1.0957, 0.9218, 0.9568,
                      0.9814, 0.9726, 0.9243, 0.9466, 1.1126, 0.9887, 0.9871, 0.9397, 0.9901,
                      1.0108, 0.9929, 1.0077, 0.9481, 0.8773, 1.0135, 0.9593, 0.9791, 1.0748,
                      0.9434, 0.8338, 0.8903, 0.9090, 0.9132, 1.0736, 0.9226, 0.9244, 0.9796,
                      0.9947, 0.9548])),
             ('2.bias',
              tensor([-0.2221, -0.0985,  0.0180, -0.0509, -0.1044, -0.1643, -0.1237,  0.0283,
                      -0.1902, -0.1166,  0.0719, -0.0428,  0.0386, -0.1292,  0.0580, -0.1769,
                      -0.0705, -0.0274, -0.0008,  0.0427, -0.1080, -0.2453, -0.0276, -0.1687,
                      -0.1751, -0.1807,  0.0636, -0.1865,  0.0561,  0.0288, -0.1937,  0.0047,
                      -0.1017, -0.0194, -0.0071, -0.1958, -0.0803,  0.0037,  0.0022, -0.1663,
                      -0.1978, -0.1249, -0.0390, -0.0362,  0.0639, -0.0119,  0.0021, -0.1438,
                       0.0074, -0.0724,  0.0635, -0.1125,  0.0177, -0.1529, -0.2221, -0.1342,
                      -0.1023,  0.0224, -0.1250,  0.0882, -0.1608, -0.1067,  0.0010, -0.0060,
                       0.0200, -0.0022, -0.0297, -0.1012, -0.0061, -0.0667, -0.1304, -0.0756,
                      -0.0179,  0.0150,  0.0035, -0.1520,  0.0604, -0.0589, -0.1608,  0.0159,
                      -0.0402, -0.0194, -0.0831, -0.0607,  0.0101, -0.1445, -0.1683,  0.0015,
                      -0.1331, -0.0055, -0.0161, -0.2462,  0.0028, -0.1583, -0.1081, -0.1371,
                      -0.1147, -0.0286, -0.0536, -0.0253, -0.0150, -0.0101, -0.1449, -0.1356,
                      -0.1570, -0.0029, -0.0533, -0.0037,  0.0403,  0.0386,  0.0193, -0.0461,
                      -0.0715, -0.0187, -0.0386,  0.0256, -0.1726, -0.0435, -0.1079, -0.0820,
                      -0.0178, -0.0508, -0.1172, -0.1566, -0.0371, -0.1853,  0.0018, -0.1542])),
             ('2.running_mean',
              tensor([-0.0323, -0.0548,  0.0515,  0.0148, -0.0287, -0.0349, -0.0234,  0.0529,
                      -0.0393, -0.0336, -0.0201, -0.0084,  0.0512, -0.0291, -0.0318, -0.0242,
                      -0.0432, -0.0206,  0.0252, -0.0384, -0.0393, -0.0334, -0.0251, -0.0294,
                      -0.0218, -0.0216, -0.0288, -0.0275, -0.0271,  0.0201, -0.0330,  0.0327,
                       0.0693, -0.0395,  0.0219, -0.0361,  0.0084, -0.0288,  0.0300, -0.0300,
                      -0.0309, -0.0131,  0.0529, -0.0391, -0.0275,  0.0193,  0.0548, -0.0166,
                       0.0738, -0.0428, -0.0279, -0.0229,  0.0539, -0.0252, -0.0114, -0.0327,
                       0.0826,  0.0378,  0.0889, -0.0073, -0.0170, -0.0201,  0.0202,  0.0144,
                       0.0310, -0.0333, -0.0451, -0.0112,  0.0474, -0.0095, -0.0229,  0.0085,
                       0.0153, -0.0199, -0.0113, -0.0303, -0.0211, -0.0280, -0.0176,  0.0546,
                      -0.0053, -0.0366, -0.0187, -0.0086,  0.0228, -0.0356,  0.0206,  0.0458,
                      -0.0194, -0.0237,  0.0131, -0.0189,  0.0363, -0.0246, -0.0380, -0.0234,
                      -0.0183,  0.0260, -0.0013,  0.0140, -0.0380, -0.0197, -0.0268, -0.0233,
                      -0.0290,  0.0028, -0.0170, -0.0164,  0.0411, -0.0243,  0.0270, -0.0550,
                      -0.0154, -0.0346, -0.0034,  0.0454, -0.0302, -0.0407,  0.1022,  0.0349,
                       0.0987, -0.0361, -0.0371, -0.0434, -0.0559, -0.0168,  0.0016, -0.0190])),
             ('2.running_var',
              tensor([0.0029, 0.0045, 0.0052, 0.0028, 0.0019, 0.0037, 0.0020, 0.0049, 0.0038,
                      0.0033, 0.0035, 0.0025, 0.0049, 0.0032, 0.0040, 0.0026, 0.0035, 0.0029,
                      0.0030, 0.0040, 0.0025, 0.0034, 0.0032, 0.0031, 0.0025, 0.0027, 0.0035,
                      0.0026, 0.0039, 0.0030, 0.0031, 0.0032, 0.0054, 0.0038, 0.0030, 0.0036,
                      0.0023, 0.0038, 0.0028, 0.0034, 0.0030, 0.0025, 0.0053, 0.0027, 0.0035,
                      0.0032, 0.0053, 0.0024, 0.0076, 0.0035, 0.0034, 0.0028, 0.0051, 0.0023,
                      0.0023, 0.0028, 0.0081, 0.0042, 0.0087, 0.0028, 0.0022, 0.0018, 0.0030,
                      0.0024, 0.0032, 0.0035, 0.0048, 0.0022, 0.0046, 0.0029, 0.0027, 0.0027,
                      0.0028, 0.0034, 0.0025, 0.0028, 0.0028, 0.0025, 0.0023, 0.0051, 0.0024,
                      0.0042, 0.0039, 0.0024, 0.0033, 0.0022, 0.0019, 0.0044, 0.0022, 0.0028,
                      0.0029, 0.0023, 0.0036, 0.0026, 0.0037, 0.0019, 0.0025, 0.0032, 0.0025,
                      0.0025, 0.0035, 0.0020, 0.0026, 0.0027, 0.0027, 0.0021, 0.0027, 0.0024,
                      0.0038, 0.0036, 0.0030, 0.0050, 0.0022, 0.0038, 0.0024, 0.0045, 0.0031,
                      0.0030, 0.0118, 0.0031, 0.0106, 0.0030, 0.0034, 0.0039, 0.0049, 0.0027,
                      0.0025, 0.0023])),
             ('2.num_batches_tracked', tensor(1365)),
             ('4.weight',
              tensor([[-0.0601,  0.0167,  0.0434,  ..., -0.0107, -0.0160, -0.0604],
                      [-0.0832,  0.0217,  0.0746,  ...,  0.0122,  0.1207,  0.0378],
                      [ 0.0302,  0.0645, -0.0110,  ..., -0.0341, -0.0806,  0.1110],
                      ...,
                      [-0.0503,  0.0568,  0.0138,  ..., -0.0620,  0.0072, -0.0221],
                      [ 0.0147, -0.0258, -0.0748,  ...,  0.0478,  0.0203,  0.0345],
                      [-0.0525,  0.0780,  0.0203,  ...,  0.0005,  0.1034,  0.0314]])),
             ('4.bias',
              tensor([ 0.1188,  0.0540, -0.0710, -0.0233, -0.0743,  0.0199,  0.0592,  0.1566,
                       0.0167,  0.0349,  0.2120, -0.1128,  0.2674,  0.1443, -0.0952,  0.0690,
                      -0.0491,  0.1164, -0.0901, -0.0742,  0.1222, -0.1206,  0.0850,  0.1899,
                      -0.0144,  0.1210, -0.1109, -0.0355, -0.0276,  0.1922,  0.0477, -0.1147,
                      -0.1292,  0.1911,  0.0670,  0.2170, -0.1015,  0.1835,  0.1489,  0.1416,
                      -0.1184,  0.1516,  0.0087,  0.2048,  0.2045,  0.1999,  0.0021,  0.2120,
                      -0.0447, -0.0133, -0.0914, -0.0310, -0.0115,  0.1307,  0.0166,  0.1351,
                      -0.0843,  0.0091,  0.1605,  0.2409, -0.1600,  0.1928,  0.0146,  0.1607])),
             ('6.weight',
              tensor([1.3587, 1.3346, 1.1795, 1.1927, 1.2387, 1.1943, 1.2951, 1.2562, 1.1537,
                      1.3265, 1.3075, 1.2001, 1.4529, 1.2722, 1.2044, 1.2082, 1.2227, 1.3761,
                      1.1972, 1.2160, 1.4331, 1.2127, 1.3919, 1.3081, 1.1894, 1.3019, 1.1584,
                      1.1468, 1.1875, 1.3659, 1.1463, 1.1827, 1.2667, 1.4171, 1.3883, 1.2964,
                      1.1533, 1.3825, 1.2318, 1.5115, 1.2595, 1.3488, 1.1594, 1.3746, 1.4498,
                      1.4010, 1.2071, 1.4393, 1.1920, 1.1499, 1.1532, 1.1144, 1.1806, 1.3433,
                      1.1810, 1.3597, 1.2381, 1.1520, 1.4748, 1.3321, 1.2760, 1.3264, 1.2211,
                      1.4812])),
             ('6.bias',
              tensor([ 0.2755,  0.2824, -0.0396, -0.0707, -0.0793, -0.0610,  0.3080,  0.2469,
                      -0.0945,  0.2679,  0.2991, -0.0601,  0.3369,  0.2401, -0.0500,  0.2459,
                      -0.0586,  0.3367, -0.0546, -0.0491,  0.3597, -0.0542,  0.3361,  0.2856,
                      -0.0511,  0.2589, -0.0470, -0.0818, -0.0559,  0.2898, -0.0580, -0.0486,
                      -0.0464,  0.3756,  0.3347,  0.2838, -0.0699,  0.3117,  0.2586,  0.3752,
                      -0.0346,  0.3181, -0.0570,  0.3511,  0.3303,  0.3742, -0.0552,  0.3320,
                      -0.0540, -0.0823, -0.0505, -0.0932, -0.0658,  0.2806, -0.0663,  0.2948,
                      -0.0129, -0.0435,  0.3628,  0.3276, -0.0281,  0.3123, -0.0552,  0.3946])),
             ('6.running_mean',
              tensor([ 0.7354,  1.1168,  0.1186,  0.1666, -0.0142,  0.1281,  0.2933,  0.5363,
                      -0.0472,  0.8753,  0.8137, -0.2523,  0.5978,  0.3210, -0.0806, -0.6033,
                       0.1897,  0.9068,  0.0714,  0.0514,  0.9141,  0.1236,  0.9450,  0.8438,
                       0.0023,  0.7475,  0.0345,  0.0649,  0.1127,  0.7650,  0.3639,  0.1484,
                       0.0286,  0.9582,  0.8084,  0.7569,  0.0378,  0.9991,  0.2242,  1.0012,
                       0.1662,  0.8041,  0.0054,  1.0280,  0.6948,  1.0287,  0.2412,  0.9451,
                      -0.0595, -0.0834,  0.0802, -0.0098,  0.0996,  0.8738, -0.0515,  0.6355,
                       0.1808,  0.0906,  0.8660,  0.8474,  0.1060,  0.7550,  0.0813,  1.0055])),
             ('6.running_var',
              tensor([1.4194, 2.2042, 0.7466, 0.9060, 0.8239, 0.9224, 0.4963, 0.8642, 0.8040,
                      1.4729, 1.5078, 0.8514, 1.1333, 0.5575, 0.7546, 0.6691, 0.7339, 1.8969,
                      0.8047, 0.8024, 2.0054, 0.7349, 1.7597, 1.6034, 0.7982, 1.4243, 0.7467,
                      0.6569, 0.6977, 1.4916, 0.7629, 0.7669, 0.8943, 1.9674, 1.4429, 1.3674,
                      0.6565, 1.7648, 0.4308, 2.0734, 0.9156, 1.4634, 0.7645, 2.2562, 1.1828,
                      1.9331, 0.6246, 1.6413, 0.6598, 0.8256, 0.7472, 0.8235, 0.8175, 1.5839,
                      1.0023, 1.0117, 0.8296, 0.7092, 1.7572, 1.3950, 0.7675, 1.4657, 1.0281,
                      2.0513])),
             ('6.num_batches_tracked', tensor(1365)),
             ('8.weight',
              tensor([[-0.3172, -0.2955,  0.1664,  0.1515,  0.1822,  0.2136, -0.2459, -0.3097,
                        0.1763, -0.3752, -0.3685,  0.2598, -0.2656, -0.3174,  0.2566, -0.2608,
                        0.2023, -0.2800,  0.2668,  0.2119, -0.2671,  0.1815, -0.3277, -0.3363,
                        0.2372, -0.3606,  0.2471,  0.2411,  0.2538, -0.3074,  0.1976,  0.2434,
                        0.1944, -0.3097, -0.2623, -0.3092,  0.2110, -0.3060, -0.2936, -0.2929,
                        0.1739, -0.3629,  0.2104, -0.3119, -0.3031, -0.2943,  0.2372, -0.2521,
                        0.2746,  0.2180,  0.2371,  0.2060,  0.2297, -0.3191,  0.1816, -0.3495,
                        0.2396,  0.2289, -0.2725, -0.3936,  0.2440, -0.3284,  0.1684, -0.2831]])),
             ('8.bias', tensor([-0.2688]))])

# Evaluate

## Training data

In [25]:
train_data = testData(
    FloatTensor(xtrain_tfidf.toarray())
)
train_loader = DataLoader(dataset=train_data, batch_size=1)

In [26]:
y_pred_list = []
# model = declare_model()
# model.load_state_dict(best_model_state)
model.eval()
with torch.no_grad():
    for X_batch in train_loader:
        # X_batch = X_batch.to(device)
        y_train_pred = model(X_batch)
        y_pred_tag = torch.round(y_train_pred)
        y_pred_list.append(y_pred_tag.cpu().numpy())

y_pred_list = [a.squeeze().tolist() for a in y_pred_list]
train_dataset['pred'] = y_pred_list

f1 = f1_score(train_dataset['label'], train_dataset['pred'])
accuracy = accuracy_score(train_dataset['label'], train_dataset['pred'])

print(f"Training F1 Score  : {round(f1, 4)} and Accuracy Score {round(accuracy, 4)}")

Training F1 Score  : 0.8252 and Accuracy Score 0.9188

## Validation data

In [27]:
val_data = testData(
    FloatTensor(xval_tfidf.toarray())
)
val_loader = DataLoader(dataset=val_data, batch_size=1)

In [28]:
y_pred_list = []
model.eval()
with torch.no_grad():
    for X_batch in val_loader:
        # X_batch = X_batch.to(device)
        y_val_pred = model(X_batch)
        y_pred_tag = torch.round(y_val_pred)
        y_pred_list.append(y_pred_tag.cpu().numpy())

y_pred_list = [a.squeeze().tolist() for a in y_pred_list]
validation_dataset['pred'] = y_pred_list

f1 = f1_score(validation_dataset['label'], validation_dataset['pred'])
accuracy = accuracy_score(validation_dataset['label'], validation_dataset['pred'])

print(f"Validation F1 Score  : {round(f1, 4)} and Accuracy Score {round(accuracy, 4)}")

Validation F1 Score  : 0.5154 and Accuracy Score 0.7509

# Submit Results

In [29]:
test_dataset['processed_text'] = test_dataset['text'].apply(
    lambda x: pre_process(x)
)
xtest_tfidf =  tfidf_vect.transform(test_dataset['processed_text'])
test_data = testData(
    FloatTensor(xtest_tfidf.toarray())
)
print(xtest_tfidf.shape)

test_loader = DataLoader(dataset=test_data, batch_size=1)

(8682, 5000)

In [30]:
y_pred_list = []
model.eval()
with torch.no_grad():
    for X_batch in test_loader:
        # X_batch = X_batch.to(device)
        y_test_pred = model(X_batch)
        y_pred_tag = torch.round(y_test_pred)
        y_pred_list.append(y_pred_tag.cpu().numpy())

y_pred_list = [a.squeeze().tolist() for a in y_pred_list]
test_dataset['label'] = y_pred_list
test_dataset.head()

                                                text  ...                                     processed_text
0  I was already over the edge with Cassie Zamora...  ...  wa alreadi edg cassi zamora show disdain two t...
1  I think you're right. She has oodles of cash a...  ...  think right ha oodl cash young grandchildren e...
2  Haha I love this. I used to give mine phone bo...  ...  haha love thi use give mine phone book room wo...
3  Probably out of desperation as they going no a...  ...                  probabl desper go answer made god
4                Sorry !! You’re real good at that!!  ...                                    sorri real good

[5 rows x 3 columns]

In [31]:
!mkdir assets

# Saving the sample submission in assets directory
if 'processed_text' in test_dataset.columns:
    test_dataset.drop(columns=['processed_text'], inplace=True)

test_dataset.to_csv(os.path.join("assets", "submission.csv"), index=False)

mkdir: cannot create directory ‘assets’: File exists

In [32]:
!aicrowd notebook submit -c emotion-detection -a assets --no-verify

Using notebook: /content/drive/MyDrive/Colab Notebooks/tfidf-ann-classifier.ipynb for submission...
Removing existing files from submission directory...
Scrubbing API keys from the notebook...
Collecting notebook...
submission.zip ━━━━━━━━━━━━━━━━━━ 100.0% • 323.8/322.2 KB • 843.1 kB/s • 0:00:00
                                                  ╭─────────────────────────╮
                                                  │ Successfully submitted! │
                                                  ╰─────────────────────────╯
                                                        Important links
┌──────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│  This submission │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection/submissions/147664              │
│                  │                                                                                                          │
│  All submissions │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection/submissions?my_submissions=true │
│                  │                                                                                                          │
│      Leaderboard │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection/leaderboards                    │
│                  │                                                                                                          │
│ Discussion forum │ https://discourse.aicrowd.com/c/ai-blitz-9                                                               │
│                  │                                                                                                          │
│   Challenge page │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection                                 │
└──────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# References

#### Tutorial - Early Stopping - Vanilla RNN - PyTorch
https://www.kaggle.com/akhileshrai/tutorial-early-stopping-vanilla-rnn-pytorch

#### PyTorch [Tabular] — Binary Classification
https://towardsdatascience.com/pytorch-tabular-binary-classification-a0368da5bb89