# Download Dataset

In [2]:
!pip install aicrowd-cli

Collecting aicrowd-cli
  Downloading https://files.pythonhosted.org/packages/1f/57/59b5a00c6e90c9cc028b3da9dff90e242ad2847e735b1a0e81a21c616e27/aicrowd_cli-0.1.7-py3-none-any.whl (49kB)
     |████████████████████████████████| 51kB 2.5MB/s
Collecting rich<11,>=10.0.0
  Downloading https://files.pythonhosted.org/packages/a8/32/eb8aadb1ed791081e5c773bd1dfa15f1a71788fbeda37b12f837f2b1999b/rich-10.3.0-py3-none-any.whl (205kB)
     |████████████████████████████████| 215kB 7.6MB/s
Collecting requests<3,>=2.25.1
  Downloading https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61kB)
     |████████████████████████████████| 61kB 6.3MB/s
Collecting tqdm<5,>=4.56.0
  Downloading https://files.pythonhosted.org/packages/b4/20/9f1e974bb4761128fc0d0a32813eaa92827309b1756c4b892d28adfb4415/tqdm-4.61.1-py2.py3-none-any.whl (75kB)
     |████████████████████████████████| 81kB 8.4MB/s
Requirement already satisfied: click<8,>=7.1.2 in /usr/local/lib/python3.7/dist-packages (from aicrowd-cli) (7.1.2)
Collecting gitpython<4,>=3.1.12
  Downloading https://files.pythonhosted.org/packages/a6/99/98019716955ba243657daedd1de8f3a88ca1f5b75057c38e959db22fb87b/GitPython-3.1.14-py3-none-any.whl (159kB)
     |████████████████████████████████| 163kB 39.3MB/s
Collecting requests-toolbelt<1,>=0.9.1
  Downloading https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl (54kB)
     |████████████████████████████████| 61kB 6.9MB/s
Requirement already satisfied: toml<1,>=0.10.2 in /usr/local/lib/python3.7/dist-packages (from aicrowd-cli) (0.10.2)
Collecting colorama<0.5.0,>=0.4.0
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Collecting commonmark<0.10.0,>=0.9.0
  Downloading https://files.pythonhosted.org/packages/b1/92/dfd892312d822f36c55366118b95d914e5f16de11044a27cf10a7d71bbbf/commonmark-0.9.1-py2.py3-none-any.whl (51kB)
     |████████████████████████████████| 51kB 5.8MB/s
Requirement already satisfied: typing-extensions<4.0.0,>=3.7.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from rich<11,>=10.0.0->aicrowd-cli) (3.7.4.3)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /usr/local/lib/python3.7/dist-packages (from rich<11,>=10.0.0->aicrowd-cli) (2.6.1)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.25.1->aicrowd-cli) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.25.1->aicrowd-cli) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.25.1->aicrowd-cli) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.25.1->aicrowd-cli) (1.24.3)
Collecting gitdb<5,>=4.0.1
  Downloading https://files.pythonhosted.org/packages/ea/e8/f414d1a4f0bbc668ed441f74f44c116d9816833a48bf81d22b697090dba8/gitdb-4.0.7-py3-none-any.whl (63kB)
     |████████████████████████████████| 71kB 7.6MB/s
Collecting smmap<5,>=3.0.1
  Downloading https://files.pythonhosted.org/packages/68/ee/d540eb5e5996eb81c26ceffac6ee49041d473bc5125f2aa995cf51ec1cf1/smmap-4.0.0-py2.py3-none-any.whl
ERROR: google-colab 1.0.0 has requirement requests~=2.23.0, but you'll have requests 2.25.1 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
Installing collected packages: colorama, commonmark, rich, requests, tqdm, smmap, gitdb, gitpython, requests-toolbelt, aicrowd-cli
  Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Found existing installation: tqdm 4.41.1
    Uninstalling tqdm-4.41.1:
      Successfully uninstalled tqdm-4.41.1
Successfully installed aicrowd-cli-0.1.7 colorama-0.4.4 commonmark-0.9.1 gitdb-4.0.7 gitpython-3.1.14 requests-2.25.1 requests-toolbelt-0.9.1 rich-10.3.0 smmap-4.0.0 tqdm-4.61.1

In [3]:
API_KEY = 'cc0a3da7611cfc6098a7bd9db11b3ecf' # Please get your your API Key from [https://www.aicrowd.com/participants/me]
!aicrowd login --api-key $API_KEY

API Key valid
Saved API Key successfully!

In [4]:
# Downloading the Dataset
!mkdir data
!aicrowd dataset download --challenge emotion-detection -j 3 -o data

train.csv:   0% 0.00/2.30M [00:00<?, ?B/s]
train.csv: 100% 2.30M/2.30M [00:00<00:00, 2.49MB/s]
val.csv:   0% 0.00/262k [00:00<?, ?B/s]
test.csv: 100% 642k/642k [00:00<00:00, 947kB/s]
val.csv: 100% 262k/262k [00:00<00:00, 518kB/s]

# Download & Import Libraries

In [5]:
!pip install emoji

Collecting emoji
  Downloading https://files.pythonhosted.org/packages/24/fa/b3368f41b95a286f8d300e323449ab4e86b85334c2e0b477e94422b8ed0f/emoji-1.2.0-py3-none-any.whl (131kB)
     |████████████████████████████████| 133kB 4.1MB/s
Installing collected packages: emoji
Successfully installed emoji-1.2.0

In [66]:
import os
import re
import emoji
import time
import pandas as pd
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import f1_score, accuracy_score
from xgboost import XGBClassifier

In [43]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

# Read Dataset

In [9]:
train_dataset = pd.read_csv("data/train.csv")
validation_dataset = pd.read_csv("data/val.csv")[1:]
test_dataset = pd.read_csv("data/test.csv")

train_dataset.head(20)

                                                 text  label
0         takes no time to copy/paste a press release      0
1                                   You're delusional      1
2   Jazz fan here. I completely feel. Lindsay Mann...      0
3   ah i was also confused but i think they mean f...      0
4             Thank you so much. ♥️ that means a lot.      0
5                                And I’ll be there!!!      0
6   There are some amazingly cringey compilations ...      0
7   Check the frame (FPS) limit option in the adva...      0
8   you made me think I was in the dbd subreddit w...      0
9                                  It was in your op.      0
10  There is a reason 15 people liked my comment d...      0
11  He's not THAT bad on YouTube, but on Twitter.....      0
12  As someone who is dairy intolerant (milk is in...      0
13  IVE NEVER BEEN MORE PROUD TO CAMPAIGN FOR A CA...      0
14  See him live if you haven’t already. One of my...      0
15  CNN has video of the arrest. Someone needs to ...      0
16  It wasn't fair on the rest of the list, nothin...      1
17  Finally got this in the mail today. I'm pretty...      0
18  Yes, once I even deleted my account because I ...      1
19  This is truly the most captivating trilogy I’v...      0

# Process text

In [44]:
stops = set(stopwords.words('english'))
porter = nltk.PorterStemmer()

def pre_process(str):
    def rm_html_tags(str):
        html_prog = re.compile(r'<[^>]+>',re.S)
        return html_prog.sub('', str)

    def rm_html_escape_characters(str):
        pattern_str = r'&quot;|&amp;|&lt;|&gt;|&nbsp;|&#34;|&#38;|&#60;|&#62;|&#160;|&#20284;|&#30524;|&#26684|&#43;|&#20540|&#23612;'
        escape_characters_prog = re.compile(pattern_str, re.S)
        return escape_characters_prog.sub('', str)

    def rm_at_user(str):
        return re.sub(r'@[a-zA-Z_0-9]*', '', str)

    def rm_url(str):
        return re.sub(r'http[s]?:[/+]?[a-zA-Z0-9_\.\/]*', '', str)

    def rm_repeat_chars(str):
        return re.sub(r'(.)(\1){2,}', r'\1\1', str)

    def rm_hashtag_symbol(str):
        return re.sub(r'#', '', str)

    def rm_time(str):
        return re.sub(r'[0-9][0-9]:[0-9][0-9]', '', str)

    def rm_punctuation(str):
        return re.sub(r'[^\w\s]', ' ', str)

    def split_emojis(str):
        text_part = ''.join(c for c in str if c not in emoji.UNICODE_EMOJI)
        emoji_part = ' '.join(c for c in str if c in emoji.UNICODE_EMOJI)
        return text_part + ' ' + emoji_part
    
    # do not change the preprocessing order only if you know what you're doing 
    str = str.lower()
    str = rm_url(str)        
    str = rm_at_user(str)        
    str = rm_repeat_chars(str) 
    str = rm_hashtag_symbol(str)       
    str = rm_time(str)
    str = rm_punctuation(str)
    # str = emoji.demojize(str, delimiters=(' emoji_', ' '))
    str = split_emojis(str)

    try:
        str = nltk.tokenize.word_tokenize(str)
        try:
            str = [porter.stem(t) for t in str]
        except:
            pass
    except:
        pass

    words = [w for w in str if w and w not in stops]
    return ' '.join(words)

In [45]:
text = "takes no time to copy/paste a press release"
pre_process(text)

'take time copi past press releas'

In [46]:
start_time = time.time()
train_dataset['processed_text'] = train_dataset['text'].apply(
    lambda x: pre_process(x)
)
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

train_dataset.head(20)

Elapsed time: 12.734 seconds

                                                 text  ...                                     processed_text
0         takes no time to copy/paste a press release  ...                   take time copi past press releas
1                                   You're delusional  ...                                           delusion
2   Jazz fan here. I completely feel. Lindsay Mann...  ...  jazz fan complet feel lindsay mann cousin ha v...
3   ah i was also confused but i think they mean f...  ...     ah wa also confus think mean friend around age
4             Thank you so much. ♥️ that means a lot.  ...                                thank much mean lot
5                                And I’ll be there!!!  ...
6   There are some amazingly cringey compilations ...  ...  amazingli cringey compil terribl dialogu thi s...
7   Check the frame (FPS) limit option in the adva...  ...  check frame fp limit option advanc graphic opt...
8   you made me think I was in the dbd subreddit w...  ...      made think wa dbd subreddit statement idk whi
9                                  It was in your op.  ...                                              wa op
10  There is a reason 15 people liked my comment d...  ...  reason 15 peopl like comment dear fifteen peop...
11  He's not THAT bad on YouTube, but on Twitter.....  ...               bad youtub twitter let say problemat
12  As someone who is dairy intolerant (milk is in...  ...  someon dairi intoler milk _everyth _ thi vegan...
13  IVE NEVER BEEN MORE PROUD TO CAMPAIGN FOR A CA...  ...  ive never proud campaign candid stg im happi c...
14  See him live if you haven’t already. One of my...  ...           see live alreadi one favorit see concert
15  CNN has video of the arrest. Someone needs to ...  ...      cnn ha video arrest someon need put cop theme
16  It wasn't fair on the rest of the list, nothin...  ...                fair rest list noth good tim horton
17  Finally got this in the mail today. I'm pretty...  ...  final got thi mail today pretti excit favorit ...
18  Yes, once I even deleted my account because I ...  ...  ye onc even delet account becaus wa nervou vot...
19  This is truly the most captivating trilogy I’v...  ...  thi truli captiv trilog ever read eager read t...

[20 rows x 3 columns]

In [50]:
start_time = time.time()
validation_dataset['processed_text'] = validation_dataset['text'].apply(
    lambda x: pre_process(x)
)
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

validation_dataset.head(20)

Elapsed time: 1.4703 seconds

                                                 text  ...                                     processed_text
1                                   im still starving  ...                                     im still starv
2   *Hey just noticed..* it's your **2nd Cakeday**...  ...               hey notic 2nd cakeday slumbishop hug
3           They just did. Check out the sticky post.  ...                                  check sticki post
4                     I hope so too, she deserves it.  ...                                        hope deserv
5   is it dangerous to take a quick photo while st...  ...             danger take quick photo stop red light
6   I’m in my second year. Still closeted. Still u...  ...  second year still closet still uncomfort bodi ...
7                  Noted, I've been looking into that  ...                                          note look
8   Thank you for saying that I just haven’t felt ...  ...                thank say felt right sad constantli
9   Screw the watch stuff, I wanna hear about the ...  ...                 screw watch stuff wan na hear porn
10  Exactly....we need a car tunnel, and then let ...  ...  exactli need car tunnel let old road allow tru...
11  Also, lay a piece of tp down BEFORE you drop y...  ...  also lay piec tp befor drop first deuc noth le...
12  Go out of your way to listen to the opening se...  ...  go way listen open segment russel wise show to...
13  It's crisp, no filler material. Interesting pr...  ...  crisp filler materi interest protagonist amaz ...
14  Im not looking to be forgiven lol. I still sta...  ...  im look forgiven lol still stand said pll onli...
15  So what should I do?? I’ve been dating her for...  ...                  date eight year confus pleas help
16  Was it? I thought it was someone from last sea...  ...  wa thought wa someon last season mayb rememb w...
17  Is it a radical opinion to say no two consenti...  ...   radic opinion say two consent adult abl kill lol
18  Yes, absolutely. "But woe to the one who betra...  ...  ye absolut woe one betray would better man nev...
19  She was acting from her emotions instead of lo...  ...      wa act emot instead logic suppos huge distain
20              Omg I just finished and I'm in awe...  ...                                     omg finish awe

[20 rows x 3 columns]

# Create TF-IDF Features

In [52]:
print(train_dataset.shape)
print(validation_dataset.shape)
combined_dataset = pd.concat([train_dataset, validation_dataset])
print(combined_dataset.shape)

(31255, 3)
(3472, 3)
(34727, 3)

In [53]:
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=5000)
tfidf_vect.fit(combined_dataset['processed_text'])

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=5000,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='\\w{1,}', tokenizer=None,
                use_idf=True, vocabulary=None)

In [54]:
start_time = time.time()
xtrain_tfidf =  tfidf_vect.transform(train_dataset['processed_text'])
xval_tfidf =  tfidf_vect.transform(validation_dataset['processed_text'])
print("Elapsed time: %s seconds" % round(time.time() - start_time, 4))

print(xtrain_tfidf.shape)
print(xval_tfidf.shape)

Elapsed time: 0.3024 seconds
(31255, 5000)
(3472, 5000)

# Train Model

In [55]:
train_dataset['label'].value_counts()

0    24718
1     6537
Name: label, dtype: int64

In [56]:
y_train = train_dataset['label'].values
y_val = validation_dataset['label'].values

In [58]:
start_time = time.time()

model = XGBClassifier(
    n_estimators=1000, subsample=0.8, colsample_bytree=0.8,
    objective='binary:logistic', scale_pos_weight=4,
    seed=27
)
eval_set = [(xval_tfidf, y_val)]

model.fit(xtrain_tfidf, y_train, early_stopping_rounds=50,
          eval_metric="auc", eval_set=eval_set, verbose=True)
print(f"Elapsed time: {round(time.time() - start_time, 4)} seconds")

[0]	validation_0-auc:0.580752
Will train until validation_0-auc hasn't improved in 50 rounds.
[1]	validation_0-auc:0.603177
[2]	validation_0-auc:0.616018
[3]	validation_0-auc:0.630068
[4]	validation_0-auc:0.630116
[5]	validation_0-auc:0.630124
[6]	validation_0-auc:0.635991
[7]	validation_0-auc:0.635917
[8]	validation_0-auc:0.640824
[9]	validation_0-auc:0.642049
[10]	validation_0-auc:0.642151
[11]	validation_0-auc:0.647737
[12]	validation_0-auc:0.646662
[13]	validation_0-auc:0.650357
[14]	validation_0-auc:0.650415
[15]	validation_0-auc:0.65044
[16]	validation_0-auc:0.659476
[17]	validation_0-auc:0.663896
[18]	validation_0-auc:0.6639
[19]	validation_0-auc:0.674468
[20]	validation_0-auc:0.674488
[21]	validation_0-auc:0.676465
[22]	validation_0-auc:0.680267
[23]	validation_0-auc:0.680256
[24]	validation_0-auc:0.680231
[25]	validation_0-auc:0.686295
[26]	validation_0-auc:0.692176
[27]	validation_0-auc:0.69432
[28]	validation_0-auc:0.694512
[29]	validation_0-auc:0.698297
[30]	validation_0-auc:0.70308
[31]	validation_0-auc:0.702154
[32]	validation_0-auc:0.703257
[33]	validation_0-auc:0.702499
[34]	validation_0-auc:0.702525
[35]	validation_0-auc:0.704567
[36]	validation_0-auc:0.705628
[37]	validation_0-auc:0.715993
[38]	validation_0-auc:0.71573
[39]	validation_0-auc:0.718353
[40]	validation_0-auc:0.725895
[41]	validation_0-auc:0.725869
[42]	validation_0-auc:0.726295
[43]	validation_0-auc:0.728216
[44]	validation_0-auc:0.728229
[45]	validation_0-auc:0.728292
[46]	validation_0-auc:0.730417
[47]	validation_0-auc:0.733777
[48]	validation_0-auc:0.739467
[49]	validation_0-auc:0.739757
[50]	validation_0-auc:0.738166
[51]	validation_0-auc:0.738301
[52]	validation_0-auc:0.739241
[53]	validation_0-auc:0.741797
[54]	validation_0-auc:0.742396
[55]	validation_0-auc:0.741969
[56]	validation_0-auc:0.742123
[57]	validation_0-auc:0.741953
[58]	validation_0-auc:0.741806
[59]	validation_0-auc:0.741464
[60]	validation_0-auc:0.743311
[61]	validation_0-auc:0.742457
[62]	validation_0-auc:0.744167
[63]	validation_0-auc:0.745013
[64]	validation_0-auc:0.744712
[65]	validation_0-auc:0.744648
[66]	validation_0-auc:0.746724
[67]	validation_0-auc:0.747157
[68]	validation_0-auc:0.747166
[69]	validation_0-auc:0.747239
[70]	validation_0-auc:0.749701
[71]	validation_0-auc:0.749509
[72]	validation_0-auc:0.751338
[73]	validation_0-auc:0.753152
[74]	validation_0-auc:0.751579
[75]	validation_0-auc:0.751701
[76]	validation_0-auc:0.751855
[77]	validation_0-auc:0.752528
[78]	validation_0-auc:0.753576
[79]	validation_0-auc:0.752937
[80]	validation_0-auc:0.753133
[81]	validation_0-auc:0.754303
[82]	validation_0-auc:0.754439
[83]	validation_0-auc:0.754577
[84]	validation_0-auc:0.755169
[85]	validation_0-auc:0.756982
[86]	validation_0-auc:0.757651
[87]	validation_0-auc:0.758609
[88]	validation_0-auc:0.758661
[89]	validation_0-auc:0.758537
[90]	validation_0-auc:0.758347
[91]	validation_0-auc:0.760036
[92]	validation_0-auc:0.759949
[93]	validation_0-auc:0.760698
[94]	validation_0-auc:0.761067
[95]	validation_0-auc:0.761095
[96]	validation_0-auc:0.762373
[97]	validation_0-auc:0.762172
[98]	validation_0-auc:0.763279
[99]	validation_0-auc:0.764143
[100]	validation_0-auc:0.765392
[101]	validation_0-auc:0.766209
[102]	validation_0-auc:0.765936
[103]	validation_0-auc:0.765447
[104]	validation_0-auc:0.766041
[105]	validation_0-auc:0.7664
[106]	validation_0-auc:0.76666
[107]	validation_0-auc:0.767207
[108]	validation_0-auc:0.76814
[109]	validation_0-auc:0.768194
[110]	validation_0-auc:0.768432
[111]	validation_0-auc:0.76871
[112]	validation_0-auc:0.768705
[113]	validation_0-auc:0.769583
[114]	validation_0-auc:0.769689
[115]	validation_0-auc:0.769858
[116]	validation_0-auc:0.770514
[117]	validation_0-auc:0.771318
[118]	validation_0-auc:0.771367
[119]	validation_0-auc:0.771274
[120]	validation_0-auc:0.772155
[121]	validation_0-auc:0.772956
[122]	validation_0-auc:0.773074
[123]	validation_0-auc:0.772996
[124]	validation_0-auc:0.772941
[125]	validation_0-auc:0.774969
[126]	validation_0-auc:0.774972
[127]	validation_0-auc:0.775236
[128]	validation_0-auc:0.776426
[129]	validation_0-auc:0.776542
[130]	validation_0-auc:0.77781
[131]	validation_0-auc:0.778496
[132]	validation_0-auc:0.779943
[133]	validation_0-auc:0.779366
[134]	validation_0-auc:0.779367
[135]	validation_0-auc:0.779461
[136]	validation_0-auc:0.779439
[137]	validation_0-auc:0.77914
[138]	validation_0-auc:0.778989
[139]	validation_0-auc:0.781794
[140]	validation_0-auc:0.782247
[141]	validation_0-auc:0.781966
[142]	validation_0-auc:0.781772
[143]	validation_0-auc:0.781879
[144]	validation_0-auc:0.78124
[145]	validation_0-auc:0.781229
[146]	validation_0-auc:0.780637
[147]	validation_0-auc:0.78071
[148]	validation_0-auc:0.78072
[149]	validation_0-auc:0.780755
[150]	validation_0-auc:0.780611
[151]	validation_0-auc:0.780631
[152]	validation_0-auc:0.782225
[153]	validation_0-auc:0.783012
[154]	validation_0-auc:0.783048
[155]	validation_0-auc:0.783327
[156]	validation_0-auc:0.783359
[157]	validation_0-auc:0.78336
[158]	validation_0-auc:0.783878
[159]	validation_0-auc:0.783984
[160]	validation_0-auc:0.784036
[161]	validation_0-auc:0.785896
[162]	validation_0-auc:0.785978
[163]	validation_0-auc:0.786018
[164]	validation_0-auc:0.786684
[165]	validation_0-auc:0.788487
[166]	validation_0-auc:0.788314
[167]	validation_0-auc:0.788314
[168]	validation_0-auc:0.788337
[169]	validation_0-auc:0.789395
[170]	validation_0-auc:0.788987
[171]	validation_0-auc:0.788599
[172]	validation_0-auc:0.789988
[173]	validation_0-auc:0.790102
[174]	validation_0-auc:0.789862
[175]	validation_0-auc:0.789535
[176]	validation_0-auc:0.790263
[177]	validation_0-auc:0.790027
[178]	validation_0-auc:0.790062
[179]	validation_0-auc:0.790055
[180]	validation_0-auc:0.790727
[181]	validation_0-auc:0.790698
[182]	validation_0-auc:0.790699
[183]	validation_0-auc:0.791058
[184]	validation_0-auc:0.791723
[185]	validation_0-auc:0.791834
[186]	validation_0-auc:0.791795
[187]	validation_0-auc:0.791724
[188]	validation_0-auc:0.791615
[189]	validation_0-auc:0.791691
[190]	validation_0-auc:0.791767
[191]	validation_0-auc:0.791743
[192]	validation_0-auc:0.791859
[193]	validation_0-auc:0.792024
[194]	validation_0-auc:0.792603
[195]	validation_0-auc:0.792652
[196]	validation_0-auc:0.792093
[197]	validation_0-auc:0.792514
[198]	validation_0-auc:0.79254
[199]	validation_0-auc:0.792573
[200]	validation_0-auc:0.792609
[201]	validation_0-auc:0.792936
[202]	validation_0-auc:0.792929
[203]	validation_0-auc:0.792641
[204]	validation_0-auc:0.793165
[205]	validation_0-auc:0.79307
[206]	validation_0-auc:0.792954
[207]	validation_0-auc:0.79306
[208]	validation_0-auc:0.793379
[209]	validation_0-auc:0.793632
[210]	validation_0-auc:0.794206
[211]	validation_0-auc:0.79434
[212]	validation_0-auc:0.794614
[213]	validation_0-auc:0.795188
[214]	validation_0-auc:0.7963
[215]	validation_0-auc:0.796436
[216]	validation_0-auc:0.796412
[217]	validation_0-auc:0.796451
[218]	validation_0-auc:0.796469
[219]	validation_0-auc:0.795814
[220]	validation_0-auc:0.795849
[221]	validation_0-auc:0.795876
[222]	validation_0-auc:0.796036
[223]	validation_0-auc:0.79622
[224]	validation_0-auc:0.796412
[225]	validation_0-auc:0.796371
[226]	validation_0-auc:0.796389
[227]	validation_0-auc:0.796183
[228]	validation_0-auc:0.796522
[229]	validation_0-auc:0.796748
[230]	validation_0-auc:0.796572
[231]	validation_0-auc:0.796834
[232]	validation_0-auc:0.797181
[233]	validation_0-auc:0.797022
[234]	validation_0-auc:0.798419
[235]	validation_0-auc:0.798409
[236]	validation_0-auc:0.798642
[237]	validation_0-auc:0.798671
[238]	validation_0-auc:0.798693
[239]	validation_0-auc:0.798663
[240]	validation_0-auc:0.799045
[241]	validation_0-auc:0.799119
[242]	validation_0-auc:0.799641
[243]	validation_0-auc:0.799701
[244]	validation_0-auc:0.800038
[245]	validation_0-auc:0.80018
[246]	validation_0-auc:0.800312
[247]	validation_0-auc:0.800587
[248]	validation_0-auc:0.80093
[249]	validation_0-auc:0.800713
[250]	validation_0-auc:0.800691
[251]	validation_0-auc:0.800978
[252]	validation_0-auc:0.801049
[253]	validation_0-auc:0.801061
[254]	validation_0-auc:0.800534
[255]	validation_0-auc:0.800818
[256]	validation_0-auc:0.801766
[257]	validation_0-auc:0.801939
[258]	validation_0-auc:0.801622
[259]	validation_0-auc:0.801703
[260]	validation_0-auc:0.801605
[261]	validation_0-auc:0.802387
[262]	validation_0-auc:0.802697
[263]	validation_0-auc:0.802765
[264]	validation_0-auc:0.80311
[265]	validation_0-auc:0.803163
[266]	validation_0-auc:0.802391
[267]	validation_0-auc:0.802228
[268]	validation_0-auc:0.802161
[269]	validation_0-auc:0.802367
[270]	validation_0-auc:0.801993
[271]	validation_0-auc:0.802287
[272]	validation_0-auc:0.80316
[273]	validation_0-auc:0.803414
[274]	validation_0-auc:0.803382
[275]	validation_0-auc:0.803431
[276]	validation_0-auc:0.803487
[277]	validation_0-auc:0.804103
[278]	validation_0-auc:0.804318
[279]	validation_0-auc:0.804655
[280]	validation_0-auc:0.804275
[281]	validation_0-auc:0.805149
[282]	validation_0-auc:0.805625
[283]	validation_0-auc:0.805708
[284]	validation_0-auc:0.805763
[285]	validation_0-auc:0.806752
[286]	validation_0-auc:0.806862
[287]	validation_0-auc:0.807009
[288]	validation_0-auc:0.807315
[289]	validation_0-auc:0.807299
[290]	validation_0-auc:0.807237
[291]	validation_0-auc:0.806855
[292]	validation_0-auc:0.807054
[293]	validation_0-auc:0.807272
[294]	validation_0-auc:0.807054
[295]	validation_0-auc:0.807077
[296]	validation_0-auc:0.807094
[297]	validation_0-auc:0.807078
[298]	validation_0-auc:0.807352
[299]	validation_0-auc:0.807552
[300]	validation_0-auc:0.807585
[301]	validation_0-auc:0.807517
[302]	validation_0-auc:0.807458
[303]	validation_0-auc:0.807441
[304]	validation_0-auc:0.807472
[305]	validation_0-auc:0.807819
[306]	validation_0-auc:0.807826
[307]	validation_0-auc:0.807865
[308]	validation_0-auc:0.807937
[309]	validation_0-auc:0.807903
[310]	validation_0-auc:0.807806
[311]	validation_0-auc:0.808127
[312]	validation_0-auc:0.808164
[313]	validation_0-auc:0.808262
[314]	validation_0-auc:0.808372
[315]	validation_0-auc:0.808237
[316]	validation_0-auc:0.808215
[317]	validation_0-auc:0.8083
[318]	validation_0-auc:0.808403
[319]	validation_0-auc:0.808206
[320]	validation_0-auc:0.808331
[321]	validation_0-auc:0.807663
[322]	validation_0-auc:0.807746
[323]	validation_0-auc:0.808127
[324]	validation_0-auc:0.808057
[325]	validation_0-auc:0.808022
[326]	validation_0-auc:0.80793
[327]	validation_0-auc:0.808001
[328]	validation_0-auc:0.808013
[329]	validation_0-auc:0.808046
[330]	validation_0-auc:0.808002
[331]	validation_0-auc:0.808172
[332]	validation_0-auc:0.808202
[333]	validation_0-auc:0.808206
[334]	validation_0-auc:0.80828
[335]	validation_0-auc:0.80864
[336]	validation_0-auc:0.808713
[337]	validation_0-auc:0.808989
[338]	validation_0-auc:0.809012
[339]	validation_0-auc:0.809024
[340]	validation_0-auc:0.809411
[341]	validation_0-auc:0.810327
[342]	validation_0-auc:0.810353
[343]	validation_0-auc:0.810087
[344]	validation_0-auc:0.809719
[345]	validation_0-auc:0.809791
[346]	validation_0-auc:0.810058
[347]	validation_0-auc:0.810097
[348]	validation_0-auc:0.810175
[349]	validation_0-auc:0.810691
[350]	validation_0-auc:0.810841
[351]	validation_0-auc:0.811038
[352]	validation_0-auc:0.811164
[353]	validation_0-auc:0.810555
[354]	validation_0-auc:0.810973
[355]	validation_0-auc:0.810594
[356]	validation_0-auc:0.810908
[357]	validation_0-auc:0.810902
[358]	validation_0-auc:0.81102
[359]	validation_0-auc:0.81107
[360]	validation_0-auc:0.811255
[361]	validation_0-auc:0.811172
[362]	validation_0-auc:0.811376
[363]	validation_0-auc:0.811593
[364]	validation_0-auc:0.811201
[365]	validation_0-auc:0.811338
[366]	validation_0-auc:0.81131
[367]	validation_0-auc:0.811474
[368]	validation_0-auc:0.811718
[369]	validation_0-auc:0.811782
[370]	validation_0-auc:0.811597
[371]	validation_0-auc:0.811466
[372]	validation_0-auc:0.811425
[373]	validation_0-auc:0.810892
[374]	validation_0-auc:0.810835
[375]	validation_0-auc:0.810996
[376]	validation_0-auc:0.811683
[377]	validation_0-auc:0.811688
[378]	validation_0-auc:0.812061
[379]	validation_0-auc:0.812119
[380]	validation_0-auc:0.811709
[381]	validation_0-auc:0.811653
[382]	validation_0-auc:0.812118
[383]	validation_0-auc:0.811869
[384]	validation_0-auc:0.811658
[385]	validation_0-auc:0.811762
[386]	validation_0-auc:0.812015
[387]	validation_0-auc:0.812158
[388]	validation_0-auc:0.812163
[389]	validation_0-auc:0.812103
[390]	validation_0-auc:0.811947
[391]	validation_0-auc:0.812139
[392]	validation_0-auc:0.81223
[393]	validation_0-auc:0.812331
[394]	validation_0-auc:0.81239
[395]	validation_0-auc:0.812681
[396]	validation_0-auc:0.812504
[397]	validation_0-auc:0.812719
[398]	validation_0-auc:0.812737
[399]	validation_0-auc:0.8125
[400]	validation_0-auc:0.812416
[401]	validation_0-auc:0.812263
[402]	validation_0-auc:0.81228
[403]	validation_0-auc:0.811925
[404]	validation_0-auc:0.812767
[405]	validation_0-auc:0.813242
[406]	validation_0-auc:0.813132
[407]	validation_0-auc:0.81369
[408]	validation_0-auc:0.813449
[409]	validation_0-auc:0.813391
[410]	validation_0-auc:0.813568
[411]	validation_0-auc:0.813583
[412]	validation_0-auc:0.813727
[413]	validation_0-auc:0.814759
[414]	validation_0-auc:0.815107
[415]	validation_0-auc:0.815088
[416]	validation_0-auc:0.815309
[417]	validation_0-auc:0.815259
[418]	validation_0-auc:0.815175
[419]	validation_0-auc:0.815164
[420]	validation_0-auc:0.815205
[421]	validation_0-auc:0.81467
[422]	validation_0-auc:0.814969
[423]	validation_0-auc:0.815026
[424]	validation_0-auc:0.814998
[425]	validation_0-auc:0.815002
[426]	validation_0-auc:0.815135
[427]	validation_0-auc:0.815213
[428]	validation_0-auc:0.815305
[429]	validation_0-auc:0.815407
[430]	validation_0-auc:0.815488
[431]	validation_0-auc:0.815892
[432]	validation_0-auc:0.81584
[433]	validation_0-auc:0.816316
[434]	validation_0-auc:0.816122
[435]	validation_0-auc:0.816104
[436]	validation_0-auc:0.816295
[437]	validation_0-auc:0.816924
[438]	validation_0-auc:0.817289
[439]	validation_0-auc:0.817656
[440]	validation_0-auc:0.817431
[441]	validation_0-auc:0.817463
[442]	validation_0-auc:0.817573
[443]	validation_0-auc:0.817516
[444]	validation_0-auc:0.817409
[445]	validation_0-auc:0.817458
[446]	validation_0-auc:0.817672
[447]	validation_0-auc:0.817987
[448]	validation_0-auc:0.818051
[449]	validation_0-auc:0.817882
[450]	validation_0-auc:0.817905
[451]	validation_0-auc:0.818132
[452]	validation_0-auc:0.818383
[453]	validation_0-auc:0.817812
[454]	validation_0-auc:0.81788
[455]	validation_0-auc:0.817974
[456]	validation_0-auc:0.818
[457]	validation_0-auc:0.81836
[458]	validation_0-auc:0.818226
[459]	validation_0-auc:0.818244
[460]	validation_0-auc:0.818342
[461]	validation_0-auc:0.818094
[462]	validation_0-auc:0.817836
[463]	validation_0-auc:0.817242
[464]	validation_0-auc:0.817457
[465]	validation_0-auc:0.817976
[466]	validation_0-auc:0.817276
[467]	validation_0-auc:0.817263
[468]	validation_0-auc:0.81736
[469]	validation_0-auc:0.817354
[470]	validation_0-auc:0.817312
[471]	validation_0-auc:0.817378
[472]	validation_0-auc:0.817409
[473]	validation_0-auc:0.817047
[474]	validation_0-auc:0.816965
[475]	validation_0-auc:0.816629
[476]	validation_0-auc:0.816718
[477]	validation_0-auc:0.816424
[478]	validation_0-auc:0.816724
[479]	validation_0-auc:0.816666
[480]	validation_0-auc:0.816672
[481]	validation_0-auc:0.816184
[482]	validation_0-auc:0.816709
[483]	validation_0-auc:0.816785
[484]	validation_0-auc:0.816904
[485]	validation_0-auc:0.816928
[486]	validation_0-auc:0.816846
[487]	validation_0-auc:0.816926
[488]	validation_0-auc:0.817198
[489]	validation_0-auc:0.817242
[490]	validation_0-auc:0.817224
[491]	validation_0-auc:0.817265
[492]	validation_0-auc:0.817266
[493]	validation_0-auc:0.817347
[494]	validation_0-auc:0.817952
[495]	validation_0-auc:0.818021
[496]	validation_0-auc:0.817943
[497]	validation_0-auc:0.818062
[498]	validation_0-auc:0.818051
[499]	validation_0-auc:0.818161
[500]	validation_0-auc:0.818255
[501]	validation_0-auc:0.818271
[502]	validation_0-auc:0.818963
[503]	validation_0-auc:0.818973
[504]	validation_0-auc:0.818251
[505]	validation_0-auc:0.818246
[506]	validation_0-auc:0.818383
[507]	validation_0-auc:0.818228
[508]	validation_0-auc:0.818222
[509]	validation_0-auc:0.818213
[510]	validation_0-auc:0.818933
[511]	validation_0-auc:0.818878
[512]	validation_0-auc:0.818813
[513]	validation_0-auc:0.818918
[514]	validation_0-auc:0.81872
[515]	validation_0-auc:0.818952
[516]	validation_0-auc:0.818739
[517]	validation_0-auc:0.818811
[518]	validation_0-auc:0.81878
[519]	validation_0-auc:0.81907
[520]	validation_0-auc:0.818955
[521]	validation_0-auc:0.819071
[522]	validation_0-auc:0.81909
[523]	validation_0-auc:0.818651
[524]	validation_0-auc:0.8187
[525]	validation_0-auc:0.819192
[526]	validation_0-auc:0.818986
[527]	validation_0-auc:0.818987
[528]	validation_0-auc:0.819108
[529]	validation_0-auc:0.819286
[530]	validation_0-auc:0.819256
[531]	validation_0-auc:0.81923
[532]	validation_0-auc:0.819337
[533]	validation_0-auc:0.819588
[534]	validation_0-auc:0.819713
[535]	validation_0-auc:0.819816
[536]	validation_0-auc:0.819862
[537]	validation_0-auc:0.819802
[538]	validation_0-auc:0.820066
[539]	validation_0-auc:0.820249
[540]	validation_0-auc:0.820178
[541]	validation_0-auc:0.820157
[542]	validation_0-auc:0.820334
[543]	validation_0-auc:0.820475
[544]	validation_0-auc:0.82067
[545]	validation_0-auc:0.820534
[546]	validation_0-auc:0.82054
[547]	validation_0-auc:0.820599
[548]	validation_0-auc:0.820368
[549]	validation_0-auc:0.820365
[550]	validation_0-auc:0.820412
[551]	validation_0-auc:0.820346
[552]	validation_0-auc:0.819919
[553]	validation_0-auc:0.819763
[554]	validation_0-auc:0.819942
[555]	validation_0-auc:0.820085
[556]	validation_0-auc:0.82008
[557]	validation_0-auc:0.820184
[558]	validation_0-auc:0.820265
[559]	validation_0-auc:0.820272
[560]	validation_0-auc:0.820266
[561]	validation_0-auc:0.820285
[562]	validation_0-auc:0.819951
[563]	validation_0-auc:0.819987
[564]	validation_0-auc:0.819905
[565]	validation_0-auc:0.819908
[566]	validation_0-auc:0.820291
[567]	validation_0-auc:0.820031
[568]	validation_0-auc:0.820198
[569]	validation_0-auc:0.820165
[570]	validation_0-auc:0.820054
[571]	validation_0-auc:0.820028
[572]	validation_0-auc:0.820214
[573]	validation_0-auc:0.820194
[574]	validation_0-auc:0.820153
[575]	validation_0-auc:0.820127
[576]	validation_0-auc:0.820102
[577]	validation_0-auc:0.820281
[578]	validation_0-auc:0.820288
[579]	validation_0-auc:0.82024
[580]	validation_0-auc:0.82001
[581]	validation_0-auc:0.819999
[582]	validation_0-auc:0.820003
[583]	validation_0-auc:0.819803
[584]	validation_0-auc:0.819731
[585]	validation_0-auc:0.819529
[586]	validation_0-auc:0.819467
[587]	validation_0-auc:0.819628
[588]	validation_0-auc:0.8196
[589]	validation_0-auc:0.81956
[590]	validation_0-auc:0.819428
[591]	validation_0-auc:0.81978
[592]	validation_0-auc:0.819896
[593]	validation_0-auc:0.81973
[594]	validation_0-auc:0.819824
Stopping. Best iteration:
[544]	validation_0-auc:0.82067

Elapsed time: 20.4398 seconds

# Evaluate Performance

In [59]:
train_dataset['pred'] = model.predict(xtrain_tfidf)
validation_dataset['pred'] = model.predict(xval_tfidf)

In [61]:
# Getting F1 & Accuracy score of training predictions
f1 = f1_score(train_dataset['label'], train_dataset['pred'])
accuracy = accuracy_score(train_dataset['label'], train_dataset['pred'])

print(f"Validation F1 Score  : {round(f1, 4)} and Accuracy Score {round(accuracy, 4)}")

Validation F1 Score  : 0.6398 and Accuracy Score 0.8345

In [62]:
# Getting F1 & Accuracy score of training predictions
f1 = f1_score(validation_dataset['label'], validation_dataset['pred'])
accuracy = accuracy_score(validation_dataset['label'], validation_dataset['pred'])

print(f"Validation F1 Score  : {round(f1, 4)} and Accuracy Score {round(accuracy, 4)}")

Validation F1 Score  : 0.5674 and Accuracy Score 0.7984

# Submit Results

In [63]:
test_dataset['processed_text'] = test_dataset['text'].apply(
    lambda x: pre_process(x)
)
xtest_tfidf =  tfidf_vect.transform(test_dataset['processed_text'])

print(xtest_tfidf.shape)

(8682, 5000)

In [64]:
test_dataset['label'] = model.predict(xtest_tfidf)
test_dataset.head()

                                                text  ...                                     processed_text
0  I was already over the edge with Cassie Zamora...  ...  wa alreadi edg cassi zamora show disdain two t...
1  I think you're right. She has oodles of cash a...  ...  think right ha oodl cash young grandchildren e...
2  Haha I love this. I used to give mine phone bo...  ...  haha love thi use give mine phone book room wo...
3  Probably out of desperation as they going no a...  ...                  probabl desper go answer made god
4                Sorry !! You’re real good at that!!  ...                                    sorri real good

[5 rows x 3 columns]

In [67]:
!mkdir assets

# Saving the sample submission in assets directory
if 'processed_text' in test_dataset.columns:
    test_dataset.drop(columns=['processed_text'], inplace=True)

test_dataset.to_csv(os.path.join("assets", "submission.csv"), index=False)

mkdir: cannot create directory ‘assets’: File exists

In [68]:
!aicrowd notebook submit -c emotion-detection -a assets --no-verify

Mounting Google Drive 💾
Your Google Drive will be mounted to access the colab notebook
Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.activity.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fexperimentsandconfigs%20https%3a%2f%2fwww.googleapis.com%2fauth%2fphotos.native&response_type=code

Enter your authorization code:
4/1AY0e-g6VNJ4fp4Dnk3t4pje_ufmUZ0OEBQamTw_wGJJDRg5WBEelO3cSPBo
Mounted at /content/drive
Using notebook: /content/drive/MyDrive/Colab Notebooks/tfidf-xgboost-classifier.ipynb for submission...
Scrubbing API keys from the notebook...
Collecting notebook...
submission.zip ━━━━━━━━━━━━━━━━━━ 100.0% • 321.7/320.1 KB • 383.2 kB/s • 0:00:00
                                                  ╭─────────────────────────╮
                                                  │ Successfully submitted! │
                                                  ╰─────────────────────────╯
                                                        Important links
┌──────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│  This submission │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection/submissions/146896              │
│                  │                                                                                                          │
│  All submissions │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection/submissions?my_submissions=true │
│                  │                                                                                                          │
│      Leaderboard │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection/leaderboards                    │
│                  │                                                                                                          │
│ Discussion forum │ https://discourse.aicrowd.com/c/ai-blitz-9                                                               │
│                  │                                                                                                          │
│   Challenge page │ https://www.aicrowd.com/challenges/ai-blitz-9/problems/emotion-detection                                 │
└──────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────┘